### ISSUE TITLE
Model.fit() throw an exception

### ISSUE THREAD

**Issue by BenjaminChoou** [apple/tensorflow_macos#123]
```
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import tensorflow as tf
from tensorflow.keras import models, layers, losses, metrics, callbacks


# random generate data
ds_data = tf.data.Dataset.from_tensor_slices(tf.constant(np.random.uniform(size=[1000, 8, 3]),dtype = tf.float32))
ds_label = tf.data.Dataset.from_tensor_slices(tf.constant(np.random.uniform(size=[1000, 3]),dtype = tf.float32))

#We put all data into one batch for better efficiency since the data volume is small.
ds_train = tf.data.Dataset.zip((ds_data,ds_label)).batch(38).cache()

tf.keras.backend.clear_session()
x_input = layers.Input(shape = (None,3),dtype = tf.float32)
x = layers.LSTM(3,return_sequences = True,input_shape=(None,3))(x_input)
x = layers.LSTM(3,return_sequences = True,input_shape=(None,3))(x)
x = layers.LSTM(3,return_sequences = True,input_shape=(None,3))(x)
x = layers.LSTM(3,input_shape=(None,3))(x)
x = layers.Dense(3)(x)

model = models.Model(inputs = [x_input],outputs = [x])
model.summary()

#Customized loss function, consider the ratio between square error and the prediction
class MSPE(losses.Loss):
    def call(self,y_true,y_pred):
        err_percent = (y_true - y_pred)**2/(tf.maximum(y_true**2,1e-7))
        mean_err_percent = tf.reduce_mean(err_percent)
        return mean_err_percent

    def get_config(self):
        config = super(MSPE, self).get_config()
        return config

import os
import datetime

optimizer = tf.keras.optimizers.Adam(learning_rate=0.01)
model.compile(optimizer=optimizer,loss=MSPE(name = "MSPE"))

stamp = datetime.datetime.now().strftime("%Y%m%d-%H%M%S")
logdir = os.path.join('data', 'autograph', stamp)

## We recommend using pathlib under Python3
# from pathlib import Path
# stamp = datetime.datetime.now().strftime("%Y%m%d-%H%M%S")
# logdir = str(Path('../../data/autograph/' + stamp))

tb_callback = tf.keras.callbacks.TensorBoard(logdir, histogram_freq=1)
#Half the learning rate if loss is not improved after 100 epoches
lr_callback = tf.keras.callbacks.ReduceLROnPlateau(monitor="loss",factor = 0.5, patience = 100)
#Stop training when loss is not improved after 200 epoches
stop_callback = tf.keras.callbacks.EarlyStopping(monitor = "loss", patience= 200)
callbacks_list = [tb_callback,lr_callback,stop_callback]

history = model.fit(ds_train,epochs=500,callbacks = callbacks_list)
```

I get the errors when I called model.filt():

```
---------------------------------------------------------------------------
InvalidArgumentError                      Traceback (most recent call last)
<ipython-input-5-68247dafd21c> in <module>
     20 callbacks_list = [tb_callback,lr_callback,stop_callback]
     21 
---> 22 history = model.fit(ds_train,epochs=500,callbacks = callbacks_list)

~/miniforge3/envs/tf24/lib/python3.8/site-packages/tensorflow/python/keras/engine/training.py in fit(self, x, y, batch_size, epochs, verbose, callbacks, validation_split, validation_data, shuffle, class_weight, sample_weight, initial_epoch, steps_per_epoch, validation_steps, validation_batch_size, validation_freq, max_queue_size, workers, use_multiprocessing)
   1098                 _r=1):
   1099               callbacks.on_train_batch_begin(step)
-> 1100               tmp_logs = self.train_function(iterator)
   1101               if data_handler.should_sync:
   1102                 context.async_wait()

~/miniforge3/envs/tf24/lib/python3.8/site-packages/tensorflow/python/eager/def_function.py in __call__(self, *args, **kwds)
    826     tracing_count = self.experimental_get_tracing_count()
    827     with trace.Trace(self._name) as tm:
--> 828       result = self._call(*args, **kwds)
    829       compiler = "xla" if self._experimental_compile else "nonXla"
    830       new_tracing_count = self.experimental_get_tracing_count()

~/miniforge3/envs/tf24/lib/python3.8/site-packages/tensorflow/python/eager/def_function.py in _call(self, *args, **kwds)
    886         # Lifting succeeded, so variables are initialized and we can run the
    887         # stateless function.
--> 888         return self._stateless_fn(*args, **kwds)
    889     else:
    890       _, _, _, filtered_flat_args = \

~/miniforge3/envs/tf24/lib/python3.8/site-packages/tensorflow/python/eager/function.py in __call__(self, *args, **kwargs)
   2940       (graph_function,
   2941        filtered_flat_args) = self._maybe_define_function(args, kwargs)
-> 2942     return graph_function._call_flat(
   2943         filtered_flat_args, captured_inputs=graph_function.captured_inputs)  # pylint: disable=protected-access
   2944 

~/miniforge3/envs/tf24/lib/python3.8/site-packages/tensorflow/python/eager/function.py in _call_flat(self, args, captured_inputs, cancellation_manager)
   1916         and executing_eagerly):
   1917       # No tape is watching; skip to running the function.
-> 1918       return self._build_call_outputs(self._inference_function.call(
   1919           ctx, args, cancellation_manager=cancellation_manager))
   1920     forward_backward = self._select_forward_and_backward_functions(

~/miniforge3/envs/tf24/lib/python3.8/site-packages/tensorflow/python/eager/function.py in call(self, ctx, args, cancellation_manager)
    553       with _InterpolateFunctionError(self):
    554         if cancellation_manager is None:
--> 555           outputs = execute.execute(
    556               str(self.signature.name),
    557               num_outputs=self._num_outputs,

~/miniforge3/envs/tf24/lib/python3.8/site-packages/tensorflow/python/eager/execute.py in quick_execute(op_name, num_outputs, inputs, attrs, ctx, name)
     57   try:
     58     ctx.ensure_initialized()
---> 59     tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
     60                                         inputs, attrs, num_outputs)
     61   except core._NotOkStatusException as e:

InvalidArgumentError:  TransposeMLCBytes: Input bytes is nil.
	 [[node gradient_tape/model/dense/MLCMatMul_1 (defined at /Users/benjaminchou/miniforge3/envs/tf24/lib/python3.8/site-packages/tensorflow/compiler/tf2mlcompute/ops/gen_mlc_ops.py:5259) ]]
	 [[MLCSubgraphOp_0_3]] [Op:__inference_train_function_1321]

Errors may have originated from an input operation.
Input Source operations connected to node gradient_tape/model/dense/MLCMatMul_1:
 gradient_tape/MSPE/sub/MLCSubGrad (defined at /Users/benjaminchou/miniforge3/envs/tf24/lib/python3.8/site-packages/tensorflow/compiler/tf2mlcompute/ops/gen_mlc_ops.py:7223)	
 model/lstm_3/Reshape (defined at <ipython-input-5-68247dafd21c>:22)

Function call stack:
train_function
```

Here are installed packages.
```
Package                       Version
----------------------------- ---------
absl-py                       0.11.0
anyio                         2.0.2
appnope                       0.1.2
argon2-cffi                   20.1.0
astunparse                    1.6.3
async-generator               1.10
attrs                         20.3.0
Babel                         2.9.0
backcall                      0.2.0
backports.functools-lru-cache 1.6.1
bleach                        3.2.1
brotlipy                      0.7.0
cached-property               1.5.2
cachetools                    4.2.0
certifi                       2020.12.5
cffi                          1.14.4
chardet                       4.0.0
cryptography                  3.3.1
cycler                        0.10.0
decorator                     4.4.2
defusedxml                    0.6.0
entrypoints                   0.3
flatbuffers                   1.12
gast                          0.3.3
google-auth                   1.24.0
google-auth-oauthlib          0.4.2
google-pasta                  0.2.0
grpcio                        1.33.2
h5py                          2.10.0
idna                          2.10
importlib-metadata            3.3.0
ipykernel                     5.4.2
ipython                       7.19.0
ipython-genutils              0.2.0
jedi                          0.18.0
Jinja2                        2.11.2
joblib                        1.0.0
json5                         0.9.5
jsonschema                    3.2.0
jupyter-client                6.1.7
jupyter-core                  4.7.0
jupyter-server                1.1.4
jupyterlab                    3.0.1
jupyterlab-pygments           0.1.2
jupyterlab-server             2.0.0
Keras-Preprocessing           1.1.2
kiwisolver                    1.3.1
Markdown                      3.3.3
MarkupSafe                    1.1.1
matplotlib                    3.3.3
mistune                       0.8.4
nbclassic                     0.2.5
nbclient                      0.5.1
nbconvert                     6.0.7
nbformat                      5.0.8
nest-asyncio                  1.4.3
notebook                      6.1.6
numpy                         1.18.5
oauthlib                      3.1.0
olefile                       0.46
opt-einsum                    3.3.0
packaging                     20.8
pandas                        1.2.0
pandocfilters                 1.4.2
parso                         0.8.1
pexpect                       4.8.0
pickleshare                   0.7.5
Pillow                        8.1.0
pip                           20.2.4
prometheus-client             0.9.0
prompt-toolkit                3.0.9
protobuf                      3.13.0
ptyprocess                    0.7.0
pyasn1                        0.4.8
pyasn1-modules                0.2.8
pycparser                     2.20
Pygments                      2.7.3
pyOpenSSL                     20.0.1
pyparsing                     2.4.7
pyrsistent                    0.17.3
PySocks                       1.7.1
python-dateutil               2.8.1
pytz                          2020.5
pyzmq                         20.0.0
requests                      2.25.1
requests-oauthlib             1.3.0
rsa                           4.6
scikit-learn                  0.24.0
scipy                         1.6.0
Send2Trash                    1.5.0
setuptools                    51.1.1
six                           1.15.0
sniffio                       1.2.0
tensorboard                   2.4.0
tensorboard-plugin-wit        1.7.0
tensorflow-addons             0.11.2
tensorflow-estimator          2.3.0
tensorflow-macos              0.1a1
termcolor                     1.1.0
terminado                     0.9.2
testpath                      0.4.4
threadpoolctl                 2.1.0
tornado                       6.1
traitlets                     5.0.5
typeguard                     2.10.0
typing-extensions             3.7.4.3
urllib3                       1.26.2
wcwidth                       0.2.5
webencodings                  0.5.1
Werkzeug                      1.0.1
wheel                         0.36.2
wrapt                         1.12.1
zipp                          3.4.0
```

**Comment by BenjaminChoou** [comment]
What is strange is that this exception disappears when I use two layer LSTM.

```
tf.keras.backend.clear_session()
x_input = layers.Input(shape = (None,3),dtype = tf.float32)
x = layers.LSTM(3,return_sequences = True,input_shape=(None,3))(x_input)
x = layers.LSTM(3,return_sequences = True,input_shape=(None,3))(x)
# x = layers.LSTM(3,return_sequences = True,input_shape=(None,3))(x)
x = layers.LSTM(3,input_shape=(None,3))(x)
x = layers.Dense(3)(x)
```

**Comment by anna-tikhonova** [comment]
Thank you very much for reporting this. We will investigate locally and report back.

**Comment by BenjaminChoou** [comment]
@anna-tikhonova 
Besides, following error occurs when I use `Dataset.cache()` in my code. I cannot fix it unless I remove `.cache()`. This won't happen in other platform like colab.
```
Traceback (most recent call last):
  File "/Users/benjaminchou/Documents/Code/SASRec_tf2/main.py", line 59, in <module>
    history = model.fit(ds_train, epochs=500, callbacks=callbacks_list)
  File "/Users/benjaminchou/miniforge3/envs/tf2/lib/python3.8/site-packages/tensorflow/python/keras/engine/training.py", line 1100, in fit
    tmp_logs = self.train_function(iterator)
  File "/Users/benjaminchou/miniforge3/envs/tf2/lib/python3.8/site-packages/tensorflow/python/eager/def_function.py", line 828, in __call__
    result = self._call(*args, **kwds)
  File "/Users/benjaminchou/miniforge3/envs/tf2/lib/python3.8/site-packages/tensorflow/python/eager/def_function.py", line 888, in _call
    return self._stateless_fn(*args, **kwds)
  File "/Users/benjaminchou/miniforge3/envs/tf2/lib/python3.8/site-packages/tensorflow/python/eager/function.py", line 2942, in __call__
    return graph_function._call_flat(
  File "/Users/benjaminchou/miniforge3/envs/tf2/lib/python3.8/site-packages/tensorflow/python/eager/function.py", line 1918, in _call_flat
    return self._build_call_outputs(self._inference_function.call(
  File "/Users/benjaminchou/miniforge3/envs/tf2/lib/python3.8/site-packages/tensorflow/python/eager/function.py", line 555, in call
    outputs = execute.execute(
  File "/Users/benjaminchou/miniforge3/envs/tf2/lib/python3.8/site-packages/tensorflow/python/eager/execute.py", line 59, in quick_execute
    tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
tensorflow.python.framework.errors_impl.InvalidArgumentError:  TransposeMLCBytes: Input bytes is nil.
	 [[node gradient_tape/model/dense/MLCMatMul_1 (defined at /miniforge3/envs/tf2/lib/python3.8/site-packages/tensorflow/compiler/tf2mlcompute/ops/gen_mlc_ops.py:5259) ]]
	 [[MLCSubgraphOp_0_3]] [Op:__inference_train_function_1321]

Errors may have originated from an input operation.
Input Source operations connected to node gradient_tape/model/dense/MLCMatMul_1:
 model/lstm_3/Reshape (defined at /Documents/Code/SASRec_tf2/main.py:59)	
 gradient_tape/MSPE/sub/MLCSubGrad (defined at /miniforge3/envs/tf2/lib/python3.8/site-packages/tensorflow/compiler/tf2mlcompute/ops/gen_mlc_ops.py:7223)

Function call stack:
train_function

2021-01-12 15:01:49.853705: W tensorflow/core/kernels/data/cache_dataset_ops.cc:757] The calling iterator did not fully read the dataset being cached. In order to avoid unexpected truncation of the dataset, the partially cached contents of the dataset will be discarded. This can happen if you have an input pipeline similar to `dataset.cache().take(k).repeat()`. You should use `dataset.take(k).cache().repeat()` instead.

```

**Comment by dimitree54** [comment]
Here is simple code to reproduce the "TransposeMLCBytes: Input bytes is nil." issue with tensorflow-macos 0.1a1:
```
import tensorflow as tf

v1 = tf.Variable(tf.ones((5, 6)))
v2 = tf.Variable(tf.ones((6, 4)))


@tf.function
def multiply(arg1, arg2):
    return tf.matmul(arg1, arg2)


with tf.GradientTape() as tape:
    loss = multiply(v1, v2)
gradients = tape.gradient(loss, [v1, v2]). # on this line "InvalidArgumentError:  TransposeMLCBytes: Input bytes is nil"
```
If I remove decorator tf.function all works. If I do not use matmul inside tf.function all works. If run the code on other machines with usual tensorflow all works.

**Comment by dimitree54** [comment]
One more interesting thing that could help find a bug. This code works.
```
import tensorflow as tf

v1 = tf.Variable(tf.ones((6, 5)))
v2 = tf.Variable(tf.ones((6, 4)))


@tf.function
def multiply(arg1, arg2):
    return tf.matmul(arg1, arg2, transpose_a=True)


with tf.GradientTape() as tape:
    loss = multiply(v1, v2)
gradients = tape.gradient(loss, [v1, v2]).  # no error
```

**Comment by dimitree54** [comment]
By the way if you wrap gradients calculation in tf.function the will be no error:
```
import tensorflow as tf

v1 = tf.Variable(tf.ones((5, 6)))
v2 = tf.Variable(tf.ones((6, 4)))
optimizer = tf.optimizers.SGD()


@tf.function
def multiply(arg1, arg2):
    return tf.matmul(arg1, arg2)


@tf.function
def run():
    with tf.GradientTape() as tape:
        loss = multiply(v1, v2)
    gradients = tape.gradient(loss, [v1, v2])
    optimizer.apply_gradients(zip(gradients, [v1, v2]))


run()  # no error
```

**Comment by zazula** [comment]
I'm seeing the exact same thing with > 3 LSTM layers.

InternalError:  TransposeMLCBytes: Input bytes is nullptr.
	 [[node gradient_tape/model_3/predictions/MLCMatMul_1 (defined at /opt/homebrew/Caskroom/miniforge/base/envs/jupyter-tf-m1/lib/python3.8/site-packages/tensorflow/compiler/tf2mlcompute/ops/gen_mlc_ops.py:5535) ]]
	 [[MLCSubgraphOp_4_1]] [Op:__inference_train_function_25712]

**Comment by c-juhwan** [comment]
Hi, I'm also having this error when I use more than 4 LSTM layers.
3 LSTM layers were fine.

My code is:
```python
model_name = 'RNN_classifier_en'
BATCH_SIZE = 128
NUM_EPOCHS = 10
VALID_SPLIT = 0.1
MAX_LEN = train_inputs.shape[1]

kargs = {'model_name': model_name,
        'vocab_size': datas['vocab_size'],
        'embedding_dimension': 100,
        'dropout_rate': 0.2,
        'lstm_dimension': 150,
        'dense_dimension': 150,
        'output_dimension': 1}


# ### Model implementation

class RNNclassifier(tf.keras.Model):
    def __init__(self, **kargs):
        super(RNNclassifier, self).__init__(name=kargs['model_name'])

        self.dropout = tf.keras.layers.Dropout(kargs['dropout_rate'])
        self.embedding = tf.keras.layers.Embedding(input_dim=kargs['vocab_size'], output_dim=kargs['embedding_dimension'])
        self.lstm1 = tf.keras.layers.LSTM(kargs['lstm_dimension'], return_sequences=True)
        self.lstm2 = tf.keras.layers.LSTM(kargs['lstm_dimension'], return_sequences=True)
        self.lstm3 = tf.keras.layers.LSTM(kargs['lstm_dimension'], return_sequences=True)
        self.lstm4 = tf.keras.layers.LSTM(kargs['lstm_dimension'])
        self.fc1 = tf.keras.layers.Dense(units=kargs['dense_dimension'], activation=tf.keras.activations.relu)
        self.fc2 = tf.keras.layers.Dense(units=1, activation=tf.keras.activations.sigmoid)

    def call(self, x):
        x = self.embedding(x)
        x = self.dropout(x)

        x = self.lstm1(x)
        x = self.lstm2(x)
        x = self.lstm3(x)
        x = self.lstm4(x)
        x = self.dropout(x)

        x = self.fc1(x)
        x = self.dropout(x)

        x = self.fc2(x)

        return x

# ### Generate model instance

model = RNNclassifier(**kargs)
model.compile(optimizer=tf.keras.optimizers.Adam(1e-4),
            loss=tf.keras.losses.BinaryCrossentropy(),
            metrics=[tf.keras.metrics.BinaryAccuracy(name='accuracy')])

# ### Model learning

earlystop_callback = tf.keras.callbacks.EarlyStopping(monitor='val_accuracy', min_delta=1e-4, patience=2)

checkpoint_path = DATA_PATH + model_name + '/weights.h5'
checkpoint_dir = os.path.dirname(checkpoint_path)

if os.path.exists(checkpoint_dir):
    pass
else:
    os.makedirs(checkpoint_dir, exist_ok=True)

cp_callback = tf.keras.callbacks.ModelCheckpoint(checkpoint_path, monitor='val_accuracy', verbose=1, save_best_only=True, save_weights_only=True)

history = model.fit(train_inputs, train_labels, batch_size=BATCH_SIZE, epochs=NUM_EPOCHS, validation_split=VALID_SPLIT, callbacks=[earlystop_callback, cp_callback])
```

When I run this code, I got the same error:
```
Traceback (most recent call last):
  File "/Users/choijuhwan/Workspace/Git_Repos/korean-hate-speech-detection/study/study1.py", line 175, in <module>
    history = model.fit(train_inputs, train_labels, batch_size=BATCH_SIZE, epochs=NUM_EPOCHS, validation_split=VALID_SPLIT, callbacks=[earlystop_callback, cp_callback])
  File "/opt/homebrew/Caskroom/miniforge/base/envs/NLP-tf/lib/python3.8/site-packages/tensorflow/python/keras/engine/training.py", line 1100, in fit
    tmp_logs = self.train_function(iterator)
  File "/opt/homebrew/Caskroom/miniforge/base/envs/NLP-tf/lib/python3.8/site-packages/tensorflow/python/eager/def_function.py", line 828, in __call__
    result = self._call(*args, **kwds)
  File "/opt/homebrew/Caskroom/miniforge/base/envs/NLP-tf/lib/python3.8/site-packages/tensorflow/python/eager/def_function.py", line 888, in _call
    return self._stateless_fn(*args, **kwds)
  File "/opt/homebrew/Caskroom/miniforge/base/envs/NLP-tf/lib/python3.8/site-packages/tensorflow/python/eager/function.py", line 2942, in __call__
    return graph_function._call_flat(
  File "/opt/homebrew/Caskroom/miniforge/base/envs/NLP-tf/lib/python3.8/site-packages/tensorflow/python/eager/function.py", line 1918, in _call_flat
    return self._build_call_outputs(self._inference_function.call(
  File "/opt/homebrew/Caskroom/miniforge/base/envs/NLP-tf/lib/python3.8/site-packages/tensorflow/python/eager/function.py", line 555, in call
    outputs = execute.execute(
  File "/opt/homebrew/Caskroom/miniforge/base/envs/NLP-tf/lib/python3.8/site-packages/tensorflow/python/eager/execute.py", line 59, in quick_execute
    tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
tensorflow.python.framework.errors_impl.InternalError:  TransposeMLCBytes: Input bytes is nullptr.
         [[node gradient_tape/RNN_classifier_en/dense_1/MLCMatMul_1 (defined at opt/homebrew/Caskroom/miniforge/base/envs/NLP-tf/lib/python3.8/site-packages/tensorflow/compiler/tf2mlcompute/ops/gen_mlc_ops.py:5535) ]]
         [[MLCSubgraphOp_0_1]] [Op:__inference_train_function_1438]

Errors may have originated from an input operation.
Input Source operations connected to node gradient_tape/RNN_classifier_en/dense_1/MLCMatMul_1:
 RNN_classifier_en/dropout/dropout_2 (defined at opt/homebrew/Caskroom/miniforge/base/envs/NLP-tf/lib/python3.8/site-packages/tensorflow/compiler/tf2mlcompute/ops/gen_mlc_ops.py:3045)
 gradient_tape/binary_crossentropy/logistic_loss/MLCSigmoidCrossEntropyWithLogitsGrad (defined at opt/homebrew/Caskroom/miniforge/base/envs/NLP-tf/lib/python3.8/site-packages/tensorflow/compiler/tf2mlcompute/ops/gen_mlc_ops.py:6685)

Function call stack:
train_function
```

Finally I tried to use 5 LSTM layers, and I got this error again.
