### ISSUE TITLE
Error after moving from x86 to M1: "Invalid reduction dimension (1 for input with 1 dimension(s))"

### ISSUE THREAD

**Issue by pdiegmann** [apple/tensorflow_macos#131]
Hi all,

first, thanks for providing this port. I just restored my old x86 mac on this new M1 mini. However, my old code seems broken, and even sample code doesn't work as expected. I'm unsure whether there's something wrong with my setup or if it's a bug in Tensorflow/Tensorflow for macOS.

**Details**:
I followed this [tutorial](https://towardsdatascience.com/multi-label-multi-class-text-classification-with-bert-transformer-and-keras-c6355eccb63a).
The code is attached below – the only change I made was switching from `train_test_split` to a hand-split via `.sample()` due to incompatibilities of scikit and ARM on macOS.
The data (consumer complaints) used for this can be found [here](http://files.consumerfinance.gov/ccdb/complaints.csv.zip).

All is run on Python 3.8.2 in the environment created by the Quick Start script.

<details>
<summary>The output is as follows:</summary>
<p>

```
Some layers from the model checkpoint at bert-base-uncased were not used when initializing TFBertModel: ['mlm___cls', 'nsp___cls']
- This IS expected if you are initializing TFBertModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing TFBertModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
All the layers of TFBertModel were initialized from the model checkpoint at bert-base-uncased.
If your task is similar to the task the model of the checkpoint was trained on, you can already use TFBertModel for predictions without further training.
WARNING:tensorflow:AutoGraph could not transform <bound method TFBertMainLayer.call of <transformers.models.bert.modeling_tf_bert.TFBertMainLayer object at 0x1219473d0>> and will run it as-is.
Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: module 'gast' has no attribute 'Index'
To silence this warning, decorate the function with @tf.autograph.experimental.do_not_convert
WARNING:tensorflow:AutoGraph could not transform <bound method TFBertEmbeddings._embedding of <transformers.models.bert.modeling_tf_bert.TFBertEmbeddings object at 0x12185e550>> and will run it as-is.
Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: module 'gast' has no attribute 'Index'
To silence this warning, decorate the function with @tf.autograph.experimental.do_not_convert
WARNING:tensorflow:AutoGraph could not transform <bound method TFBertEncoder.call of <transformers.models.bert.modeling_tf_bert.TFBertEncoder object at 0x121858970>> and will run it as-is.
Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: module 'gast' has no attribute 'Index'
To silence this warning, decorate the function with @tf.autograph.experimental.do_not_convert
WARNING:tensorflow:AutoGraph could not transform <bound method TFBertLayer.call of <transformers.models.bert.modeling_tf_bert.TFBertLayer object at 0x121852ca0>> and will run it as-is.
Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: module 'gast' has no attribute 'Index'
To silence this warning, decorate the function with @tf.autograph.experimental.do_not_convert
WARNING:tensorflow:AutoGraph could not transform <bound method TFBertAttention.call of <transformers.models.bert.modeling_tf_bert.TFBertAttention object at 0x121852d60>> and will run it as-is.
Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: module 'gast' has no attribute 'Index'
To silence this warning, decorate the function with @tf.autograph.experimental.do_not_convert
WARNING:tensorflow:AutoGraph could not transform <bound method TFBertPooler.call of <transformers.models.bert.modeling_tf_bert.TFBertPooler object at 0x121858a60>> and will run it as-is.
Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: module 'gast' has no attribute 'Index'
To silence this warning, decorate the function with @tf.autograph.experimental.do_not_convert
Model: "BERT_MultiLabel_MultiClass"
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
==================================================================================================
input_ids (InputLayer)          [(None, 100)]        0                                            
__________________________________________________________________________________________________
bert (TFBertMainLayer)          TFBaseModelOutputWit 109482240   input_ids[0][0]                  
__________________________________________________________________________________________________
pooled_output (Dropout)         (None, 768)          0           bert[0][1]                       
__________________________________________________________________________________________________
issue (Dense)                   (None, 159)          122271      pooled_output[0][0]              
__________________________________________________________________________________________________
product (Dense)                 (None, 18)           13842       pooled_output[0][0]              
==================================================================================================
Total params: 109,618,353
Trainable params: 109,618,353
Non-trainable params: 0
__________________________________________________________________________________________________
2021-01-17 13:03:10.736431: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:116] None of the MLIR optimization passes are enabled (registered 2)
2021-01-17 13:03:10.739284: W tensorflow/core/platform/profile_utils/cpu_utils.cc:126] Failed to get CPU frequency: 0 Hz
Epoch 1/3
2021-01-17 13:03:40.572843: W tensorflow/core/framework/op_kernel.cc:1775] OP_REQUIRES failed at reduction_ops_common.h:148 : Invalid argument: Invalid reduction dimension (1 for input with 1 dimension(s)
2021-01-17 13:03:42.495224: W tensorflow/core/framework/op_kernel.cc:1775] OP_REQUIRES failed at reduction_ops_common.h:148 : Invalid argument: Invalid reduction dimension (1 for input with 1 dimension(s)
2021-01-17 13:03:43.518552: W tensorflow/core/framework/op_kernel.cc:1775] OP_REQUIRES failed at reduction_ops_common.h:148 : Invalid argument: Invalid reduction dimension (1 for input with 1 dimension(s)
2021-01-17 13:03:45.978072: W tensorflow/core/framework/op_kernel.cc:1775] OP_REQUIRES failed at reduction_ops_common.h:148 : Invalid argument: Invalid reduction dimension (1 for input with 1 dimension(s)
2021-01-17 13:03:46.924586: W tensorflow/core/framework/op_kernel.cc:1775] OP_REQUIRES failed at reduction_ops_common.h:148 : Invalid argument: Invalid reduction dimension (1 for input with 1 dimension(s)
2021-01-17 13:03:48.710859: W tensorflow/core/framework/op_kernel.cc:1775] OP_REQUIRES failed at reduction_ops_common.h:148 : Invalid argument: Invalid reduction dimension (1 for input with 1 dimension(s)
2021-01-17 13:03:50.023022: W tensorflow/core/framework/op_kernel.cc:1775] OP_REQUIRES failed at reduction_ops_common.h:148 : Invalid argument: Invalid reduction dimension (1 for input with 1 dimension(s)
2021-01-17 13:03:51.996223: W tensorflow/core/framework/op_kernel.cc:1775] OP_REQUIRES failed at reduction_ops_common.h:148 : Invalid argument: Invalid reduction dimension (1 for input with 1 dimension(s)
2021-01-17 13:03:53.743448: W tensorflow/core/framework/op_kernel.cc:1775] OP_REQUIRES failed at reduction_ops_common.h:148 : Invalid argument: Invalid reduction dimension (1 for input with 1 dimension(s)
2021-01-17 13:03:56.123983: W tensorflow/core/framework/op_kernel.cc:1775] OP_REQUIRES failed at reduction_ops_common.h:148 : Invalid argument: Invalid reduction dimension (1 for input with 1 dimension(s)
2021-01-17 13:03:57.364217: W tensorflow/core/framework/op_kernel.cc:1775] OP_REQUIRES failed at reduction_ops_common.h:148 : Invalid argument: Invalid reduction dimension (1 for input with 1 dimension(s)
2021-01-17 13:04:00.328436: W tensorflow/core/framework/op_kernel.cc:1775] OP_REQUIRES failed at reduction_ops_common.h:148 : Invalid argument: Invalid reduction dimension (1 for input with 1 dimension(s)
2021-01-17 13:04:01.821333: W tensorflow/core/framework/op_kernel.cc:1775] OP_REQUIRES failed at reduction_ops_common.h:148 : Invalid argument: Invalid reduction dimension (1 for input with 1 dimension(s)
2021-01-17 13:04:05.156143: W tensorflow/core/framework/op_kernel.cc:1775] OP_REQUIRES failed at reduction_ops_common.h:148 : Invalid argument: Invalid reduction dimension (1 for input with 1 dimension(s)
2021-01-17 13:04:06.535694: W tensorflow/core/framework/op_kernel.cc:1775] OP_REQUIRES failed at reduction_ops_common.h:148 : Invalid argument: Invalid reduction dimension (1 for input with 1 dimension(s)
2021-01-17 13:04:09.363757: W tensorflow/core/framework/op_kernel.cc:1775] OP_REQUIRES failed at reduction_ops_common.h:148 : Invalid argument: Invalid reduction dimension (1 for input with 1 dimension(s)
2021-01-17 13:04:10.756134: W tensorflow/core/framework/op_kernel.cc:1775] OP_REQUIRES failed at reduction_ops_common.h:148 : Invalid argument: Invalid reduction dimension (1 for input with 1 dimension(s)
2021-01-17 13:04:13.359131: W tensorflow/core/framework/op_kernel.cc:1775] OP_REQUIRES failed at reduction_ops_common.h:148 : Invalid argument: Invalid reduction dimension (1 for input with 1 dimension(s)
2021-01-17 13:04:14.765434: W tensorflow/core/framework/op_kernel.cc:1775] OP_REQUIRES failed at reduction_ops_common.h:148 : Invalid argument: Invalid reduction dimension (1 for input with 1 dimension(s)
2021-01-17 13:04:18.154979: W tensorflow/core/framework/op_kernel.cc:1775] OP_REQUIRES failed at reduction_ops_common.h:148 : Invalid argument: Invalid reduction dimension (1 for input with 1 dimension(s)
2021-01-17 13:04:19.260039: W tensorflow/core/framework/op_kernel.cc:1775] OP_REQUIRES failed at reduction_ops_common.h:148 : Invalid argument: Invalid reduction dimension (1 for input with 1 dimension(s)
2021-01-17 13:04:22.349153: W tensorflow/core/framework/op_kernel.cc:1775] OP_REQUIRES failed at reduction_ops_common.h:148 : Invalid argument: Invalid reduction dimension (1 for input with 1 dimension(s)
2021-01-17 13:04:23.840666: W tensorflow/core/framework/op_kernel.cc:1775] OP_REQUIRES failed at reduction_ops_common.h:148 : Invalid argument: Invalid reduction dimension (1 for input with 1 dimension(s)
2021-01-17 13:04:26.958036: W tensorflow/core/framework/op_kernel.cc:1775] OP_REQUIRES failed at reduction_ops_common.h:148 : Invalid argument: Invalid reduction dimension (1 for input with 1 dimension(s)
2021-01-17 13:04:28.413519: W tensorflow/core/framework/op_kernel.cc:1775] OP_REQUIRES failed at reduction_ops_common.h:148 : Invalid argument: Invalid reduction dimension (1 for input with 1 dimension(s)
Traceback (most recent call last):
  File "original.py", line 107, in <module>
    history = model.fit(
  File "~/tensorflow_macos_venv/lib/python3.8/site-packages/tensorflow/python/keras/engine/training.py", line 1100, in fit
    tmp_logs = self.train_function(iterator)
  File "~/tensorflow_macos_venv/lib/python3.8/site-packages/tensorflow/python/eager/def_function.py", line 828, in __call__
    result = self._call(*args, **kwds)
  File "~/tensorflow_macos_venv/lib/python3.8/site-packages/tensorflow/python/eager/def_function.py", line 888, in _call
    return self._stateless_fn(*args, **kwds)
  File "~/tensorflow_macos_venv/lib/python3.8/site-packages/tensorflow/python/eager/function.py", line 2942, in __call__
    return graph_function._call_flat(
  File "~/tensorflow_macos_venv/lib/python3.8/site-packages/tensorflow/python/eager/function.py", line 1918, in _call_flat
    return self._build_call_outputs(self._inference_function.call(
  File "~/tensorflow_macos_venv/lib/python3.8/site-packages/tensorflow/python/eager/function.py", line 555, in call
    outputs = execute.execute(
  File "~/tensorflow_macos_venv/lib/python3.8/site-packages/tensorflow/python/eager/execute.py", line 59, in quick_execute
    tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
tensorflow.python.framework.errors_impl.InvalidArgumentError:  Invalid reduction dimension (1 for input with 1 dimension(s)
         [[node Adam/clip_by_norm_196/Sum (defined at original.py:107) ]] [Op:__inference_train_function_19103]

Function call stack:
train_function
```

</p>
</details>  

Any help is greatly appreciated!

<details>
<summary>The code:</summary>
<p>

```Python
#######################################
### -------- Load libraries ------- ###
# Load Huggingface transformers
from transformers import TFBertModel,  BertConfig, BertTokenizerFast
# Then what you need from tensorflow.keras
from tensorflow.keras.layers import Input, Dropout, Dense
from tensorflow.keras.models import Model
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.callbacks import EarlyStopping
from tensorflow.keras.initializers import TruncatedNormal
from tensorflow.keras.losses import CategoricalCrossentropy
from tensorflow.keras.metrics import CategoricalAccuracy
from tensorflow.keras.utils import to_categorical
# And pandas for data import + sklearn because you allways need sklearn
import pandas as pd
#from sklearn.model_selection import train_test_split

#######################################
### --------- Import data --------- ###
# Import data from csv
data = pd.read_csv('data/complaints.csv')
# Select required columns
data = data[['Consumer complaint narrative', 'Product', 'Issue']]
# Remove a row if any of the three remaining columns are missing
data = data.dropna()
# Remove rows, where the label is present only ones (can't be split)
data = data.groupby('Issue').filter(lambda x : len(x) > 1)
data = data.groupby('Product').filter(lambda x : len(x) > 1)
# Set your model output as categorical and save in new label col
data['Issue_label'] = pd.Categorical(data['Issue'])
data['Product_label'] = pd.Categorical(data['Product'])
# Transform your output to numeric
data['Issue'] = data['Issue_label'].cat.codes
data['Product'] = data['Product_label'].cat.codes
# Split into train and test - stratify over Issue
#data, data_test = train_test_split(data, test_size = 0.2, stratify = data[['Issue']])
data_test = data.sample(frac=.3, random_state=42)
data_train = data.drop(data_test.index)
data = data_test

#######################################
### --------- Setup BERT ---------- ###
# Name of the BERT model to use
model_name = 'bert-base-uncased'
# Max length of tokens
max_length = 100
# Load transformers config and set output_hidden_states to False
config = BertConfig.from_pretrained(model_name)
config.output_hidden_states = False
# Load BERT tokenizer
tokenizer = BertTokenizerFast.from_pretrained(pretrained_model_name_or_path = model_name, config = config)
# Load the Transformers BERT model
transformer_model = TFBertModel.from_pretrained(model_name, config = config)

#######################################
### ------- Build the model ------- ###
# TF Keras documentation: https://www.tensorflow.org/api_docs/python/tf/keras/Model
# Load the MainLayer
bert = transformer_model.layers[0]
# Build your model input
input_ids = Input(shape=(max_length,), name='input_ids', dtype='int32')
inputs = {'input_ids': input_ids}
# Load the Transformers BERT model as a layer in a Keras model
bert_model = bert(inputs)[1]
dropout = Dropout(config.hidden_dropout_prob, name='pooled_output')
pooled_output = dropout(bert_model, training=False)
# Then build your model output
issue = Dense(units=len(data.Issue_label.value_counts()), kernel_initializer=TruncatedNormal(stddev=config.initializer_range), name='issue')(pooled_output)
product = Dense(units=len(data.Product_label.value_counts()), kernel_initializer=TruncatedNormal(stddev=config.initializer_range), name='product')(pooled_output)
outputs = {'issue': issue, 'product': product}
# And combine it all in a model object
model = Model(inputs=inputs, outputs=outputs, name='BERT_MultiLabel_MultiClass')
# Take a look at the model
model.summary()

#######################################
### ------- Train the model ------- ###
# Set an optimizer
optimizer = Adam(
    learning_rate=5e-05,
    epsilon=1e-08,
    decay=0.01,
    clipnorm=1.0)
# Set loss and metrics
loss = {'issue': CategoricalCrossentropy(from_logits = True), 'product': CategoricalCrossentropy(from_logits = True)}
metric = {'issue': CategoricalAccuracy('accuracy'), 'product': CategoricalAccuracy('accuracy')}
# Compile the model
model.compile(
    optimizer = optimizer,
    loss = loss, 
    metrics = metric)
# Ready output data for the model
y_issue = to_categorical(data['Issue'])
y_product = to_categorical(data['Product'])
# Tokenize the input (takes some time)
x = tokenizer(
    text=data['Consumer complaint narrative'].to_list(),
    add_special_tokens=True,
    max_length=max_length,
    truncation=True,
    padding=True, 
    return_tensors='tf',
    return_token_type_ids = False,
    return_attention_mask = False,
    verbose = True)
# Fit the model
history = model.fit(
    x={'input_ids': x['input_ids']},
    y={'issue': y_issue, 'product': y_product},
    validation_split=0.2,
    batch_size=64,
    epochs=3)

#######################################
### ----- Evaluate the model ------ ###
# Ready test data
test_y_issue = to_categorical(data_test['Issue'])
test_y_product = to_categorical(data_test['Product'])
test_x = tokenizer(
    text=data_test['Consumer complaint narrative'].to_list(),
    add_special_tokens=True,
    max_length=max_length,
    truncation=True,
    padding=True, 
    return_tensors='tf',
    return_token_type_ids = False,
    return_attention_mask = False,
    verbose = True)
# Run evaluation
model_eval = model.evaluate(
    x={'input_ids': test_x['input_ids']},
    y={'issue': test_y_issue, 'product': test_y_product}
)
```

</p>
</details>

<details>
<summary>Installed packages</summary>

<p>

via `pip list`

```
Package                Version                   Location
---------------------- ------------------------- ----------------------------
absl-py                0.11.0
appnope                0.1.2
astunparse             1.6.3
backcall               0.2.0
cached-property        1.5.2
cachetools             4.2.0
certifi                2020.12.5
chardet                4.0.0
click                  7.1.2
Cython                 0.29.21
decorator              4.4.2
filelock               3.0.12
flatbuffers            1.12
gast                   0.4.0
google-auth            1.24.0
google-auth-oauthlib   0.4.2
google-pasta           0.2.0
grpcio                 1.33.2
h5py                   2.10.0
idna                   2.10
ipykernel              5.4.3
ipython                7.19.0
ipython-genutils       0.2.0
jedi                   0.18.0
joblib                 1.0.0
jupyter-client         6.1.11
jupyter-core           4.7.0
Keras-Preprocessing    1.1.2
Markdown               3.3.3
numpy                  1.18.5
oauthlib               3.1.0
opt-einsum             3.3.0
packaging              20.8
pandas                 1.3.0.dev0+457.gc5b4272ed 
parso                  0.8.1
pexpect                4.8.0
pickleshare            0.7.5
pip                    20.3.3
prompt-toolkit         3.0.10
protobuf               3.14.0
ptyprocess             0.7.0
pyasn1                 0.4.8
pyasn1-modules         0.2.8
Pygments               2.7.4
pyparsing              2.4.7
python-dateutil        2.8.1
pytz                   2020.5
pyzmq                  21.0.1
regex                  2020.11.13
requests               2.25.1
requests-oauthlib      1.3.0
rsa                    4.7
sacremoses             0.0.43
setuptools             51.3.1
six                    1.15.0
tensorboard            2.4.1
tensorboard-plugin-wit 1.7.0
tensorflow-addons      0.11.2
tensorflow-estimator   2.4.0
tensorflow-hub         0.11.0
tensorflow-macos       0.1a1
termcolor              1.1.0
threadpoolctl          2.1.0
tokenizers             0.9.4
tornado                6.1
tqdm                   4.56.0
traitlets              5.0.5
transformers           4.3.0.dev0
typeguard              2.10.0
typing-extensions      3.7.4.3
urllib3                1.26.2
wcwidth                0.2.5
Werkzeug               1.0.1
wheel                  0.36.2
wrapt                  1.12.1
```
</p>
</details>

**Comment by pdiegmann** [comment]
FYI, I tried the same Code on Google Colab with a GPU and it runs just fine. I'll attach the output once it finishes the third epoch and evaluation.

**Comment by anna-tikhonova** [comment]
Thank you very much for reporting this and providing a reproducible test case. We will investigate and report back.
