### ISSUE TITLE
installing on an exsisting env issue

### ISSUE THREAD

**Issue by david-tao-as01** [apple/tensorflow_macos#149]
```
ERROR: Exception:
Traceback (most recent call last):
  File "/Library/Python/3.8/lib/python3.8/site-packages/pip/_internal/cli/base_command.py", line 228, in _main
    status = self.run(options, args)
  File "/Library/Python/3.8/lib/python3.8/site-packages/pip/_internal/cli/req_command.py", line 182, in wrapper
    return func(self, options, args)
  File "/Library/Python/3.8/lib/python3.8/site-packages/pip/_internal/commands/install.py", line 455, in run
    self._handle_target_dir(
  File "/Library/Python/3.8/lib/python3.8/site-packages/pip/_internal/commands/install.py", line 463, in _handle_target_dir
    ensure_dir(target_dir)
  File "/Library/Python/3.8/lib/python3.8/site-packages/pip/_internal/utils/misc.py", line 114, in ensure_dir
    os.makedirs(path)
  File "/Library/Python/3.8/lib/python3.8/os.py", line 213, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/Library/Python/3.8/lib/python3.8/os.py", line 213, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/Library/Python/3.8/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
OSError: [Errno 30] Read-only file system: '/lib'
```

I kept getting this error after it finished numpy's installation.
Tried to change the permission of the whole folder but it doesn't work.

Trying to install it on conda-forge-arm64 platform at python 3.8.6 .

**Comment by hoytak** [comment]
First, I don't recommend installing experimental packages into the system python directories using sudo, as that can mess up the system python installation and cause lots and lots of pain.  Installing it into a user virtual env would be much safer.   To do that, simply pass in another non-system path that you have write access to, and it will work fine. 

That said, /Library/Python/3.8 isn't the location of the system python environment; that gets installed into  /Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/.  /Library/Python/3.8 doesn't exist, and system integrity protection doesn't allow even root to create it outside of some standard installation paths.  (There is an issue in the command line tools python's sysconfig where it improperly reports the python library path as /Library/Python/3.8 instead of /Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/, and perhaps this is where the path you're using comes from.)
