### ISSUE TITLE
Data augmentation error

### ISSUE THREAD

**Issue by shreyasdangare** [apple/tensorflow_macos#151]
Getting error while execution this block of code on M1 MBP Python 3.8.6

`data_augmentation = keras.Sequential(
  [
    layers.experimental.preprocessing.RandomFlip("horizontal", 
                                                 input_shape=(img_height, 
                                                              img_width,
                                                              3)),
    layers.experimental.preprocessing.RandomRotation(0.1),
    layers.experimental.preprocessing.RandomZoom(0.1),
  ]
)`

**Error Message:-**
NotImplementedError                       Traceback (most recent call last)
<ipython-input-25-c8e0063429ed> in <module>
----> 1 data_augmentation = keras.Sequential(
      2   [
      3     layers.experimental.preprocessing.RandomFlip("horizontal", 
      4                                                  input_shape=(img_height, 
      5                                                               img_width,

~/miniforge3/envs/python38/lib/python3.8/site-packages/tensorflow/python/training/tracking/base.py in _method_wrapper(self, *args, **kwargs)
    515     self._self_setattr_tracking = False  # pylint: disable=protected-access
    516     try:
--> 517       result = method(self, *args, **kwargs)
    518     finally:
    519       self._self_setattr_tracking = previous_value  # pylint: disable=protected-access

~/miniforge3/envs/python38/lib/python3.8/site-packages/tensorflow/python/keras/engine/sequential.py in __init__(self, layers, name)
    142         layers = [layers]
    143       for layer in layers:
--> 144         self.add(layer)
    145 
    146   @property

~/miniforge3/envs/python38/lib/python3.8/site-packages/tensorflow/python/training/tracking/base.py in _method_wrapper(self, *args, **kwargs)
    515     self._self_setattr_tracking = False  # pylint: disable=protected-access
    516     try:
--> 517       result = method(self, *args, **kwargs)
    518     finally:
    519       self._self_setattr_tracking = previous_value  # pylint: disable=protected-access

~/miniforge3/envs/python38/lib/python3.8/site-packages/tensorflow/python/keras/engine/sequential.py in add(self, layer)
    221       # If the model is being built continuously on top of an input layer:
    222       # refresh its output.
--> 223       output_tensor = layer(self.outputs[0])
    224       if len(nest.flatten(output_tensor)) != 1:
    225         raise ValueError(SINGLE_LAYER_OUTPUT_ERROR_MSG)

~/miniforge3/envs/python38/lib/python3.8/site-packages/tensorflow/python/keras/engine/base_layer.py in __call__(self, *args, **kwargs)
    944     # >> model = tf.keras.Model(inputs, outputs)
    945     if _in_functional_construction_mode(self, inputs, args, kwargs, input_list):
--> 946       return self._functional_construction_call(inputs, args, kwargs,
    947                                                 input_list)
    948 

~/miniforge3/envs/python38/lib/python3.8/site-packages/tensorflow/python/keras/engine/base_layer.py in _functional_construction_call(self, inputs, args, kwargs, input_list)
   1083           layer=self, inputs=inputs, build_graph=True, training=training_value):
   1084         # Check input assumptions set after layer building, e.g. input shape.
-> 1085         outputs = self._keras_tensor_symbolic_call(
   1086             inputs, input_masks, args, kwargs)
   1087 

~/miniforge3/envs/python38/lib/python3.8/site-packages/tensorflow/python/keras/engine/base_layer.py in _keras_tensor_symbolic_call(self, inputs, input_masks, args, kwargs)
    815       return nest.map_structure(keras_tensor.KerasTensor, output_signature)
    816     else:
--> 817       return self._infer_output_signature(inputs, args, kwargs, input_masks)
    818 
    819   def _infer_output_signature(self, inputs, args, kwargs, input_masks):

~/miniforge3/envs/python38/lib/python3.8/site-packages/tensorflow/python/keras/engine/base_layer.py in _infer_output_signature(self, inputs, args, kwargs, input_masks)
    856           # TODO(kaftan): do we maybe_build here, or have we already done it?
    857           self._maybe_build(inputs)
--> 858           outputs = call_fn(inputs, *args, **kwargs)
    859 
    860         self._handle_activity_regularization(inputs, outputs)

~/miniforge3/envs/python38/lib/python3.8/site-packages/tensorflow/python/keras/layers/preprocessing/image_preprocessing.py in call(self, inputs, training)
    864           interpolation=self.interpolation)
    865 
--> 866     output = control_flow_util.smart_cond(training, random_rotated_inputs,
    867                                           lambda: inputs)
    868     output.set_shape(inputs.shape)

~/miniforge3/envs/python38/lib/python3.8/site-packages/tensorflow/python/keras/utils/control_flow_util.py in smart_cond(pred, true_fn, false_fn, name)
    112     return control_flow_ops.cond(
    113         pred, true_fn=true_fn, false_fn=false_fn, name=name)
--> 114   return smart_module.smart_cond(
    115       pred, true_fn=true_fn, false_fn=false_fn, name=name)
    116 

~/miniforge3/envs/python38/lib/python3.8/site-packages/tensorflow/python/framework/smart_cond.py in smart_cond(pred, true_fn, false_fn, name)
     52   if pred_value is not None:
     53     if pred_value:
---> 54       return true_fn()
     55     else:
     56       return false_fn()

~/miniforge3/envs/python38/lib/python3.8/site-packages/tensorflow/python/keras/layers/preprocessing/image_preprocessing.py in random_rotated_inputs()
    859       return transform(
    860           inputs,
--> 861           get_rotation_matrix(angles, img_hd, img_wd),
    862           fill_mode=self.fill_mode,
    863           fill_value=self.fill_value,

~/miniforge3/envs/python38/lib/python3.8/site-packages/tensorflow/python/keras/layers/preprocessing/image_preprocessing.py in get_rotation_matrix(angles, image_height, image_width, name)
    755             math_ops.cos(angles)[:, None],
    756             y_offset[:, None],
--> 757             array_ops.zeros((num_angles, 2), dtypes.float32),
    758         ],
    759         axis=1)

~/miniforge3/envs/python38/lib/python3.8/site-packages/tensorflow/python/util/dispatch.py in wrapper(*args, **kwargs)
    199     """Call target, and fall back on dispatchers if there is a TypeError."""
    200     try:
--> 201       return target(*args, **kwargs)
    202     except (TypeError, ValueError):
    203       # Note: convert_to_eager_tensor currently raises a ValueError, not a

~/miniforge3/envs/python38/lib/python3.8/site-packages/tensorflow/python/ops/array_ops.py in wrapped(*args, **kwargs)
   2817 
   2818   def wrapped(*args, **kwargs):
-> 2819     tensor = fun(*args, **kwargs)
   2820     tensor._is_zeros_tensor = True
   2821     return tensor

~/miniforge3/envs/python38/lib/python3.8/site-packages/tensorflow/python/ops/array_ops.py in zeros(shape, dtype, name)
   2866           # Create a constant if it won't be very big. Otherwise create a fill
   2867           # op to prevent serialized GraphDefs from becoming too large.
-> 2868           output = _constant_if_small(zero, shape, dtype, name)
   2869           if output is not None:
   2870             return output

~/miniforge3/envs/python38/lib/python3.8/site-packages/tensorflow/python/ops/array_ops.py in _constant_if_small(value, shape, dtype, name)
   2802 def _constant_if_small(value, shape, dtype, name):
   2803   try:
-> 2804     if np.prod(shape) < 1000:
   2805       return constant(value, shape=shape, dtype=dtype, name=name)
   2806   except TypeError:

<__array_function__ internals> in prod(*args, **kwargs)

~/miniforge3/envs/python38/lib/python3.8/site-packages/numpy/core/fromnumeric.py in prod(a, axis, dtype, out, keepdims, initial, where)
   3028     10
   3029     """
-> 3030     return _wrapreduction(a, np.multiply, 'prod', axis, dtype, out,
   3031                           keepdims=keepdims, initial=initial, where=where)
   3032 

~/miniforge3/envs/python38/lib/python3.8/site-packages/numpy/core/fromnumeric.py in _wrapreduction(obj, ufunc, method, axis, dtype, out, **kwargs)
     85                 return reduction(axis=axis, out=out, **passkwargs)
     86 
---> 87     return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
     88 
     89 

~/miniforge3/envs/python38/lib/python3.8/site-packages/tensorflow/python/framework/ops.py in __array__(self)
    850 
    851   def __array__(self):
--> 852     raise NotImplementedError(
    853         "Cannot convert a symbolic Tensor ({}) to a numpy array."
    854         " This error may indicate that you're trying to pass a Tensor to"

NotImplementedError: Cannot convert a symbolic Tensor (random_rotation_1/rotation_matrix/strided_slice:0) to a numpy array. This error may indicate that you're trying to pass a Tensor to a NumPy call, which is not supported

The entire code can be found at [https://www.tensorflow.org/tutorials/images/classification](url)

**Comment by anna-tikhonova** [comment]
Thank you very much for reporting this! We will investigate locally and report back.

**Comment by sahin-abdullah** [comment]
I have the same error for the same example.

**Comment by danielmatthewsgrout** [comment]
I have a different example but very similar error:

I followed the M1 install instructions to the letter.

```
Traceback (most recent call last):
  File "pos_tagging.py", line 147, in <module>
    x = layers.Bidirectional(layers.LSTM(EMBEDDING_DIM,return_sequences=True))(x) 
  File "/Users/daniel/miniforge3/envs/tens/lib/python3.8/site-packages/tensorflow/python/keras/layers/wrappers.py", line 567, in __call__
    return super(Bidirectional, self).__call__(inputs, **kwargs)
  File "/Users/daniel/miniforge3/envs/tens/lib/python3.8/site-packages/tensorflow/python/keras/engine/base_layer.py", line 946, in __call__
    return self._functional_construction_call(inputs, args, kwargs,
  File "/Users/daniel/miniforge3/envs/tens/lib/python3.8/site-packages/tensorflow/python/keras/engine/base_layer.py", line 1085, in _functional_construction_call
    outputs = self._keras_tensor_symbolic_call(
  File "/Users/daniel/miniforge3/envs/tens/lib/python3.8/site-packages/tensorflow/python/keras/engine/base_layer.py", line 817, in _keras_tensor_symbolic_call
    return self._infer_output_signature(inputs, args, kwargs, input_masks)
  File "/Users/daniel/miniforge3/envs/tens/lib/python3.8/site-packages/tensorflow/python/keras/engine/base_layer.py", line 858, in _infer_output_signature
    outputs = call_fn(inputs, *args, **kwargs)
  File "/Users/daniel/miniforge3/envs/tens/lib/python3.8/site-packages/tensorflow/python/keras/layers/wrappers.py", line 688, in call
    y = self.forward_layer(forward_inputs,
  File "/Users/daniel/miniforge3/envs/tens/lib/python3.8/site-packages/tensorflow/python/keras/layers/recurrent.py", line 660, in __call__
    return super(RNN, self).__call__(inputs, **kwargs)
  File "/Users/daniel/miniforge3/envs/tens/lib/python3.8/site-packages/tensorflow/python/keras/engine/base_layer.py", line 1007, in __call__
    outputs = call_fn(inputs, *args, **kwargs)
  File "/Users/daniel/miniforge3/envs/tens/lib/python3.8/site-packages/tensorflow/python/keras/layers/recurrent_v2.py", line 1163, in call
    inputs, initial_state, _ = self._process_inputs(inputs, initial_state, None)
  File "/Users/daniel/miniforge3/envs/tens/lib/python3.8/site-packages/tensorflow/python/keras/layers/recurrent.py", line 859, in _process_inputs
    initial_state = self.get_initial_state(inputs)
  File "/Users/daniel/miniforge3/envs/tens/lib/python3.8/site-packages/tensorflow/python/keras/layers/recurrent.py", line 642, in get_initial_state
    init_state = get_initial_state_fn(
  File "/Users/daniel/miniforge3/envs/tens/lib/python3.8/site-packages/tensorflow/python/keras/layers/recurrent.py", line 2506, in get_initial_state
    return list(_generate_zero_filled_state_for_cell(
  File "/Users/daniel/miniforge3/envs/tens/lib/python3.8/site-packages/tensorflow/python/keras/layers/recurrent.py", line 2987, in _generate_zero_filled_state_for_cell
    return _generate_zero_filled_state(batch_size, cell.state_size, dtype)
  File "/Users/daniel/miniforge3/envs/tens/lib/python3.8/site-packages/tensorflow/python/keras/layers/recurrent.py", line 3003, in _generate_zero_filled_state
    return nest.map_structure(create_zeros, state_size)
  File "/Users/daniel/miniforge3/envs/tens/lib/python3.8/site-packages/tensorflow/python/util/nest.py", line 659, in map_structure
    structure[0], [func(*x) for x in entries],
  File "/Users/daniel/miniforge3/envs/tens/lib/python3.8/site-packages/tensorflow/python/util/nest.py", line 659, in <listcomp>
    structure[0], [func(*x) for x in entries],
  File "/Users/daniel/miniforge3/envs/tens/lib/python3.8/site-packages/tensorflow/python/keras/layers/recurrent.py", line 3000, in create_zeros
    return array_ops.zeros(init_state_size, dtype=dtype)
  File "/Users/daniel/miniforge3/envs/tens/lib/python3.8/site-packages/tensorflow/python/util/dispatch.py", line 201, in wrapper
    return target(*args, **kwargs)
  File "/Users/daniel/miniforge3/envs/tens/lib/python3.8/site-packages/tensorflow/python/ops/array_ops.py", line 2819, in wrapped
    tensor = fun(*args, **kwargs)
  File "/Users/daniel/miniforge3/envs/tens/lib/python3.8/site-packages/tensorflow/python/ops/array_ops.py", line 2868, in zeros
    output = _constant_if_small(zero, shape, dtype, name)
  File "/Users/daniel/miniforge3/envs/tens/lib/python3.8/site-packages/tensorflow/python/ops/array_ops.py", line 2804, in _constant_if_small
    if np.prod(shape) < 1000:
  File "<__array_function__ internals>", line 5, in prod
  File "/Users/daniel/miniforge3/envs/tens/lib/python3.8/site-packages/numpy/core/fromnumeric.py", line 3030, in prod
    return _wrapreduction(a, np.multiply, 'prod', axis, dtype, out,
  File "/Users/daniel/miniforge3/envs/tens/lib/python3.8/site-packages/numpy/core/fromnumeric.py", line 87, in _wrapreduction
    return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
  File "/Users/daniel/miniforge3/envs/tens/lib/python3.8/site-packages/tensorflow/python/framework/ops.py", line 852, in __array__
    raise NotImplementedError(
NotImplementedError: Cannot convert a symbolic Tensor (bidirectional/forward_lstm/strided_slice:0) to a numpy array. This error may indicate that you're trying to pass a Tensor to a NumPy call, which is not supported
```

**Comment by shreyasdangare** [comment]
@danielmatthewsgrout try executing the same code without using LSTM or GRU. I thinks they are not yet implemented.

**Comment by danielmatthewsgrout** [comment]
I have a workaround:  in the environment.yaml (or whatever you called it) change numpy to numpy=1.19.5.

It's a version issue.

**Comment by shreyasdangare** [comment]
Thanks for the workaround. Although it runs into many memory errors while training even though I reduced the batch size.

**Comment by shreyasdangare** [comment]
Thanks for the workaround. Although it runs into many memory errors while training CNNs even after reducing batch size.
