### ISSUE TITLE
Running into module 'gast' has no attribute 'Index'

### ISSUE THREAD

**Issue by jantuitman** [apple/tensorflow_macos#163]
I tried to run the transformer example from the TensorFlow tutorials in this fork. it does not work, 
seems to be fixed in the real TensorFlow.
https://github.com/tensorflow/tensorflow/issues/44146

so can you please merge this?

my error:

WARNING:tensorflow:AutoGraph could not transform <function train_step at 0x1211a69d0> and will run it as-is.
Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: module 'gast' has no attribute 'Index'
To silence this warning, decorate the function with @tf.autograph.experimental.do_not_convert
WARNING:tensorflow:AutoGraph could not transform <bound method Encoder.call of <__main__.Encoder object at 0x1211a30a0>> and will run it as-is.
Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: module 'gast' has no attribute 'Index'
To silence this warning, decorate the function with @tf.autograph.experimental.do_not_convert
WARNING:tensorflow:AutoGraph could not transform <bound method MultiHeadAttention.call of <__main__.MultiHeadAttention object at 0x1211e7100>> and will run it as-is.
Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: module 'gast' has no attribute 'Index'
To silence this warning, decorate the function with @tf.autograph.experimental.do_not_convert
WARNING:tensorflow:AutoGraph could not transform <bound method Decoder.call of <__main__.Decoder object at 0x1211a3c10>> and will run it as-is.
Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: module 'gast' has no attribute 'Index'
To silence this warning, decorate the function with @tf.autograph.experimental.do_not_convert
Traceback (most recent call last):
  File "experiment.py", line 509, in <module>
    train_step(inp, tar)
  File "/Users/jantuitman/Documents/projects/math_transformer_test/venv/lib/python3.8/site-packages/tensorflow/python/eager/def_function.py", line 828, in __call__
    result = self._call(*args, **kwds)
  File "/Users/jantuitman/Documents/projects/math_transformer_test/venv/lib/python3.8/site-packages/tensorflow/python/eager/def_function.py", line 871, in _call
    self._initialize(args, kwds, add_initializers_to=initializers)
  File "/Users/jantuitman/Documents/projects/math_transformer_test/venv/lib/python3.8/site-packages/tensorflow/python/eager/def_function.py", line 725, in _initialize
    self._stateful_fn._get_concrete_function_internal_garbage_collected(  # pylint: disable=protected-access
  File "/Users/jantuitman/Documents/projects/math_transformer_test/venv/lib/python3.8/site-packages/tensorflow/python/eager/function.py", line 2969, in _get_concrete_function_internal_garbage_collected
    graph_function, _ = self._maybe_define_function(args, kwargs)
  File "/Users/jantuitman/Documents/projects/math_transformer_test/venv/lib/python3.8/site-packages/tensorflow/python/eager/function.py", line 3361, in _maybe_define_function
    graph_function = self._create_graph_function(args, kwargs)
  File "/Users/jantuitman/Documents/projects/math_transformer_test/venv/lib/python3.8/site-packages/tensorflow/python/eager/function.py", line 3196, in _create_graph_function
    func_graph_module.func_graph_from_py_func(
  File "/Users/jantuitman/Documents/projects/math_transformer_test/venv/lib/python3.8/site-packages/tensorflow/python/framework/func_graph.py", line 990, in func_graph_from_py_func
    func_outputs = python_func(*func_args, **func_kwargs)
  File "/Users/jantuitman/Documents/projects/math_transformer_test/venv/lib/python3.8/site-packages/tensorflow/python/eager/def_function.py", line 634, in wrapped_fn
    out = weak_wrapped_fn().__wrapped__(*args, **kwds)
  File "/Users/jantuitman/Documents/projects/math_transformer_test/venv/lib/python3.8/site-packages/tensorflow/python/framework/func_graph.py", line 977, in wrapper
    raise e.ag_error_metadata.to_exception(e)
TypeError: in user code:

    experiment.py:318 call  *
        dec_output, attention_weights = self.decoder(
    /Users/jantuitman/Documents/projects/math_transformer_test/venv/lib/python3.8/site-packages/tensorflow/python/keras/engine/base_layer.py:1007 __call__  **
        outputs = call_fn(inputs, *args, **kwargs)
    experiment.py:288 call  **
        x, block1, block2 = self.dec_layers[i](x, enc_output, training,

    TypeError: cannot unpack non-iterable NoneType object

**Comment by anna-tikhonova** [comment]
Thank you very much for reporting this. We will take a look at what is required to get this model to work.

**Comment by jantuitman** [comment]
Do you need any data? At what time do you plan to update this repo as I see no new commits in the last week? 

I just want to get my expectation level right, since I recently learned that Google is moving away from Tensorflow. Apple also has other frameworks, so is this repo going to be updated or is it a project that has low priority within Apple and should I look for other solutions if I want to do machine learning (on M1)?

**Comment by zachcoleman** [comment]
I downgraded gast to 0.3.3 (`pip install gast==0.3.3`) and it resolved the issue for me.

**Comment by giostefa** [comment]
I am running into the same problem and maybe the issue has to do with slicing tensors.

Simple code that fails to work:
```
import tensorflow as tf

c = tf.Variable([[1., 5.], [2., 4.]])

@tf.function
def toy_fct(x):
    #y = tf.stack([x[0,:], x[1,:]], axis=0)
    y = x[0]
    return y

toy_fct(c)
```

I will try to downgrade gast, as different people have suggested, to see if it will resolve the issue.

**Comment by zachcoleman** [comment]
@giostefa That example you wrote works for me w/ latest installation and downgrading `gast` to avoid `'gast' has no attribute Index` errors.

**Comment by giostefa** [comment]
@zachcoleman Ok, maybe I'll try to use the nightly build of tensorflow as conda has some trouble downgrading gast.
