### ISSUE TITLE
import errir

### ISSUE THREAD

**Issue by pekoWang** [apple/tensorflow_macos#225]

**Comment by pekoWang** [comment]
I suddenly cannot run import tensorflow (either in terminal or pycharm),The following is the specific error:
```
>>> import tensorflow
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/pkwang/tensorflow_macos_venv/lib/python3.8/site-packages/tensorflow/__init__.py", line 41, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "/Users/pkwang/tensorflow_macos_venv/lib/python3.8/site-packages/tensorflow/python/__init__.py", line 41, in <module>
    from tensorflow.python.eager import context
  File "/Users/pkwang/tensorflow_macos_venv/lib/python3.8/site-packages/tensorflow/python/eager/context.py", line 35, in <module>
    from tensorflow.python import pywrap_tfe
  File "/Users/pkwang/tensorflow_macos_venv/lib/python3.8/site-packages/tensorflow/python/pywrap_tfe.py", line 29, in <module>
    from tensorflow.python._pywrap_tfe import *
ImportError: dlopen(/Users/pkwang/tensorflow_macos_venv/lib/python3.8/site-packages/tensorflow/python/_pywrap_tfe.so, 2): Library not loaded: @rpath/_pywrap_tensorflow_internal.so
  Referenced from: /Users/pkwang/tensorflow_macos_venv/lib/python3.8/site-packages/tensorflow/python/_pywrap_tfe.so
  Reason: image not found
```

**Comment by pekoWang** [comment]
I tried to check the python version,but everything is normal:
```
 % file $(which python3)
/usr/bin/python3: Mach-O universal binary with 2 architectures: [x86_64:Mach-O 64-bit executable x86_64] [arm64e:Mach-O 64-bit executable arm64e]
/usr/bin/python3 (for architecture x86_64): Mach-O 64-bit executable x86_64
/usr/bin/python3 (for architecture arm64e): Mach-O 64-bit executable arm64e
```
