### ISSUE TITLE
Cannot open jupyter notebook or import tensorflow on Mac M1

### ISSUE THREAD

**Issue by RemeAjayi** [apple/tensorflow_macos#242]
Hello, 

I have successfully installed tensorflow on macos using the instructions on the github repo and this [tutorial.](https://www.ai-buzz.com/18-steps-to-install-tensorflow_macos-on-m1-macbook-2020/) I created a virtual environment and in that environment, tensorflow and jupyter notebook are listed as packages installed.

However, when I switch to python 3 in the terminal and type import tensorflow. I get failed to run tensorflow runtime. And more importantly when I run `jupyter notebook ` I get 

`Traceback (most recent call last):
  File "/Users/olohireme/miniforge3/envs/tensorflow_macos/bin/jupyter-notebook", line 5, in <module>
    from notebook.notebookapp import main
  File "/Users/olohireme/miniforge3/envs/tensorflow_macos/lib/python3.8/site-packages/notebook/notebookapp.py", line 78, in <module>
    from .services.kernels.kernelmanager import MappingKernelManager, AsyncMappingKernelManager
  File "/Users/olohireme/miniforge3/envs/tensorflow_macos/lib/python3.8/site-packages/notebook/services/kernels/kernelmanager.py", line 18, in <module>
    from jupyter_client.session import Session
  File "/Users/olohireme/miniforge3/envs/tensorflow_macos/lib/python3.8/site-packages/jupyter_client/__init__.py", line 4, in <module>
    from .connect import *
  File "/Users/olohireme/miniforge3/envs/tensorflow_macos/lib/python3.8/site-packages/jupyter_client/connect.py", line 21, in <module>
    import zmq
  File "/Users/olohireme/miniforge3/envs/tensorflow_macos/lib/python3.8/site-packages/zmq/__init__.py", line 50, in <module>
    _load_libzmq()
  File "/Users/olohireme/miniforge3/envs/tensorflow_macos/lib/python3.8/site-packages/zmq/__init__.py", line 28, in _load_libzmq
    from . import libzmq
ImportError: dlopen(/Users/olohireme/miniforge3/envs/tensorflow_macos/lib/python3.8/site-packages/zmq/libzmq.cpython-38-darwin.so, 10): no suitable image found.  Did find:
	/Users/olohireme/miniforge3/envs/tensorflow_macos/lib/python3.8/site-packages/zmq/libzmq.cpython-38-darwin.so: mach-o, but wrong architecture
	/Users/olohireme/miniforge3/envs/tensorflow_macos/lib/python3.8/site-packages/zmq/libzmq.cpython-38-darwin.so: mach-o, but wrong architecture`

Please what am I doing wrong? This is my second day of trying to get this to work.

**Comment by arge-7** [comment]
Are you positive you downloaded the ARM64 version and not the intel? Looks like you might have mixed them up.

Can you import tensorflow in your terminal or other IDE? Is this specific to Jupyter?

**Comment by RemeAjayi** [comment]
Thank you so much for responding. Yes, I downloaded the ARM64 version.  
This was the final command I used to install tensorflow. It references the ARM64 version.
`pip install --upgrade 0t "$env/lib/python3.8/site-packages/" --n0-dependencies --force "$libs/tensorflow_macos-0.1a3-cp38-cp38-macosx_11_0_arm64.whl"`
I cannot import tensorflow in Visual Studio Code. It is not specific to jupyter. Opening jupyter is another issue, the stack trace above is what I get why I try to open jupyter. I cannot open jupyter right now. Please let me know if you have any other questions. Thanks!

**Comment by RemeAjayi** [comment]
After following the steps in this[ post ](https://github.com/apple/tensorflow_macos/issues/146)

I realised that the python version in my virtual environment is for x86. 

`% file $(which python)
/Users/olohireme/miniforge3/envs/tensorflow_macos/bin/python: Mach-O 64-bit executable x86_64
`

I have gone through that post and researched. I do not understand how to change it to ARM.

**Comment by arge-7** [comment]
I'm not familiar with that tutorial. Try starting from scratch with this one, which has worked for me multiple times. It's straight from Apple's TF repo.

https://github.com/apple/tensorflow_macos/issues/153

**Comment by ManuelSchneid3r** [comment]
@arge-7 it "works", but do you get GPU acceleration?

**Comment by devnev39** [comment]
Did you have installed this tensorflow with mini forge. It looks like you used pip which don't have any supported libraries. If not consider uninstalling all and installing with mini forge conda as given in the tutorial.
