### ISSUE TITLE
ERROR: Failed building wheel for wrapt

### ISSUE THREAD

**Issue by iwasnothing** [apple/tensorflow_macos#30]
Building wheels for collected packages: wrapt
  Building wheel for wrapt (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /Users/kahingleung/tensorflow_macos_venv/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/47/db7p_9vx019c0hsxzt6vjxl00000gn/T/pip-install-5q7ejel1/wrapt/setup.py'"'"'; __file__='"'"'/private/var/folders/47/db7p_9vx019c0hsxzt6vjxl00000gn/T/pip-install-5q7ejel1/wrapt/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /private/var/folders/47/db7p_9vx019c0hsxzt6vjxl00000gn/T/pip-wheel-w0brsxw3
       cwd: /private/var/folders/47/db7p_9vx019c0hsxzt6vjxl00000gn/T/pip-install-5q7ejel1/wrapt/
  Complete output (56 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.macosx-10.9-x86_64-3.8
  creating build/lib.macosx-10.9-x86_64-3.8/wrapt
  copying src/wrapt/importer.py -> build/lib.macosx-10.9-x86_64-3.8/wrapt
  copying src/wrapt/__init__.py -> build/lib.macosx-10.9-x86_64-3.8/wrapt
  copying src/wrapt/wrappers.py -> build/lib.macosx-10.9-x86_64-3.8/wrapt
  copying src/wrapt/decorators.py -> build/lib.macosx-10.9-x86_64-3.8/wrapt
  running build_ext
  building 'wrapt._wrappers' extension
  creating build/temp.macosx-10.9-x86_64-3.8
  creating build/temp.macosx-10.9-x86_64-3.8/src
  creating build/temp.macosx-10.9-x86_64-3.8/src/wrapt
  gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -arch x86_64 -g -I/Users/kahingleung/tensorflow_macos_venv/include -I/Library/Frameworks/Python.framework/Versions/3.8/include/python3.8 -c src/wrapt/_wrappers.c -o build/temp.macosx-10.9-x86_64-3.8/src/wrapt/_wrappers.o
  gcc -bundle -undefined dynamic_lookup -arch x86_64 -g build/temp.macosx-10.9-x86_64-3.8/src/wrapt/_wrappers.o -o build/lib.macosx-10.9-x86_64-3.8/wrapt/_wrappers.cpython-38-darwin.so
  installing to build/bdist.macosx-10.9-x86_64/wheel
  running install
  running install_lib
  creating build/bdist.macosx-10.9-x86_64
  creating build/bdist.macosx-10.9-x86_64/wheel
  creating build/bdist.macosx-10.9-x86_64/wheel/wrapt
  copying build/lib.macosx-10.9-x86_64-3.8/wrapt/_wrappers.cpython-38-darwin.so -> build/bdist.macosx-10.9-x86_64/wheel/wrapt
  copying build/lib.macosx-10.9-x86_64-3.8/wrapt/importer.py -> build/bdist.macosx-10.9-x86_64/wheel/wrapt
  copying build/lib.macosx-10.9-x86_64-3.8/wrapt/__init__.py -> build/bdist.macosx-10.9-x86_64/wheel/wrapt
  copying build/lib.macosx-10.9-x86_64-3.8/wrapt/wrappers.py -> build/bdist.macosx-10.9-x86_64/wheel/wrapt
  copying build/lib.macosx-10.9-x86_64-3.8/wrapt/decorators.py -> build/bdist.macosx-10.9-x86_64/wheel/wrapt
  running install_egg_info
  running egg_info
  creating src/wrapt.egg-info
  writing src/wrapt.egg-info/PKG-INFO
  writing dependency_links to src/wrapt.egg-info/dependency_links.txt
  writing top-level names to src/wrapt.egg-info/top_level.txt
  writing manifest file 'src/wrapt.egg-info/SOURCES.txt'
  reading manifest file 'src/wrapt.egg-info/SOURCES.txt'
  writing manifest file 'src/wrapt.egg-info/SOURCES.txt'
  Copying src/wrapt.egg-info to build/bdist.macosx-10.9-x86_64/wheel/wrapt-1.12.1-py3.8.egg-info
  running install_scripts
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/private/var/folders/47/db7p_9vx019c0hsxzt6vjxl00000gn/T/pip-install-5q7ejel1/wrapt/setup.py", line 102, in <module>
      run_setup(with_extensions=True)
    File "/private/var/folders/47/db7p_9vx019c0hsxzt6vjxl00000gn/T/pip-install-5q7ejel1/wrapt/setup.py", line 72, in run_setup
      setup(**setup_kwargs_tmp)
    File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/distutils/dist.py", line 966, in run_commands
      self.run_command(cmd)
    File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/Users/kahingleung/tensorflow_macos_venv/lib/python3.8/site-packages/wheel/bdist_wheel.py", line 328, in run
      impl_tag, abi_tag, plat_tag = self.get_tag()
    File "/Users/kahingleung/tensorflow_macos_venv/lib/python3.8/site-packages/wheel/bdist_wheel.py", line 278, in get_tag
      assert tag in supported_tags, "would build wheel with unsupported tag {}".format(tag)
  AssertionError: would build wheel with unsupported tag ('cp38', 'cp38', 'macosx_11_0_x86_64')
  ----------------------------------------
  ERROR: Failed building wheel for wrapt

**Comment by visionscaper** [comment]
I experience the same problem when TF for Mac is installed in a virtual environment.

**Comment by SjDuque** [comment]
I had this same issue when trying to install it with an Anaconda environment on my Intel-Based Mac. 

To resolve I:

1. Downloaded the tensorflow_macos-0.1alpha0.tar.gz archive at [https://github.com/apple/tensorflow_macos/releases](https://github.com/apple/tensorflow_macos/releases)
2. Extracted the .tar.gz
3. Opened the terminal and entered the following:
`Downloads/tensorflow_macos/install_venv.sh -p --python=/usr/bin/python3`. I made sure to just choose the default options.


I believe the issue arises because it expects the python version installed by Xcode, which is version 3.8.2.

Hope that helps.

(I'm new to answering GitHub Issues forgive my format if it is sloppy.)

**Comment by visionscaper** [comment]
That worked @SjDuque, thanks.

**Comment by iwasnothing** [comment]
That worked.  Thanks @SjDuque

**Comment by RPHllc** [comment]
That worked, I believe the removal of "/bin/bash" did the trick. I tried with it before and it had the same issue.

**Comment by letalvoj** [comment]
> I believe the issue arises because it expects the python version installed by Xcode, which is version 3.8.2.

You saved me, thx. With XCode installed a quicker way to create the `venv` might be

```zsh
/usr/bin/python3 -m venv $PROJECT_FOLDER/venv
```
