### ISSUE TITLE
Shape mismatch in up_sampling2d/MLCUpsample2D.

### ISSUE THREAD

**Issue by Andreasgejlm** [apple/tensorflow_macos#42]
The code I'm trying to run:

```
from decoder.zplanedecoder import zPlaneDecoder
from PropagationLayer.PropagationLayer import PropagationLayer`
from CustomLoss.CustomLoss import CustomLoss
import tensorflow as tf
from tensorflow.keras import Model, Input, layers, optimizers, utils
tf.compat.v1.disable_eager_execution()

decoder = zPlaneDecoder()

training_data = decoder.get_training_data()
val_data = decoder.get_validation_data()

# 1 level down U-Net
train_in = Input((decoder.M, decoder.M, decoder.nz), name='Input', batch_size=16)
x = layers.Conv2D(128, (3, 3), activation='relu', padding='same')(train_in)
x = layers.MaxPooling2D((2, 2))(x)
x = layers.Conv2D(256, (3, 3), activation='relu', padding='same')(x)
x = layers.UpSampling2D()(x)
x = layers.Conv2D(128, (3, 3), activation='relu', padding='same')(x)

real_branch = layers.Conv2D(128, (3, 3), activation='relu', padding='same')(x)
real_branch = layers.Conv2D(1, (3, 3), activation='relu', padding='same', name="real")(real_branch)
imag_branch = layers.Conv2D(128, (3, 3), activation='relu', padding='same')(x)
imag_branch = layers.Conv2D(1, (3, 3), activation='relu', padding='same', name="imag")(imag_branch)

prop_layer = PropagationLayer(decoder.nz, decoder.M, decoder.wl, decoder.l0, (decoder.xw, decoder.yw), decoder.lp, decoder.dz)([real_branch, imag_branch])

model = Model(train_in, prop_layer)
model.compile(optimizer=optimizers.Adam(), loss=CustomLoss(), metrics=['acc'])
model.fit(training_data, training_data, epochs=3, batch_size=16, validation_data=(val_data, val_data))
```

Produces an error that does not occur when I run the code in pyenv with Tensorflow 2.3.1.

Input data is (256, 256, 3), and if I print out the shape of x before and after the upsampling layer, output is what I expect:
`(16, 128, 128, 256)`
`(16, 256, 256, 256)`

I'm running on a 2018 MacBook Pro 15" Radeon Pro 555X.

> Traceback (most recent call last):
  File "/Users/andreas/tensorflow_macos_venv/lib/python3.8/site-packages/tensorflow/python/framework/ops.py", line 755, in set_shape
    pywrap_tf_session.TF_GraphSetTensorShape_wrapper(
tensorflow.python.framework.errors_impl.InvalidArgumentError: Dimension 2 in both shapes must be equal, but are 256 and 128. Shapes are [16,128,256,256] and [16,128,128,256].

> During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/Users/andreas/tensorflow_macos_venv/lib/python3.8/site-packages/tensorflow/python/ops/gradients_util.py", line 712, in _GradientsHelper
    in_grad.set_shape(t_in.get_shape())
  File "/Users/andreas/tensorflow_macos_venv/lib/python3.8/site-packages/tensorflow/python/framework/ops.py", line 762, in set_shape
    raise ValueError(str(e))
ValueError: Dimension 2 in both shapes must be equal, but are 256 and 128. Shapes are [16,128,256,256] and [16,128,128,256].

> During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/Users/andreas/Google Drev/Speciale/Private/ML/Beam scanner/BeamScanner.py", line 34, in <module>
    model.fit(training_data, training_data, epochs=3, batch_size=16, validation_data=(val_data, val_data))
  File "/Users/andreas/tensorflow_macos_venv/lib/python3.8/site-packages/tensorflow/python/keras/engine/training_v1.py", line 789, in fit
    return func.fit(
  File "/Users/andreas/tensorflow_macos_venv/lib/python3.8/site-packages/tensorflow/python/keras/engine/training_arrays_v1.py", line 647, in fit
    return fit_loop(
  File "/Users/andreas/tensorflow_macos_venv/lib/python3.8/site-packages/tensorflow/python/keras/engine/training_arrays_v1.py", line 185, in model_iteration
    f = _make_execution_function(model, mode)
  File "/Users/andreas/tensorflow_macos_venv/lib/python3.8/site-packages/tensorflow/python/keras/engine/training_arrays_v1.py", line 555, in _make_execution_function
    return model._make_execution_function(mode)
  File "/Users/andreas/tensorflow_macos_venv/lib/python3.8/site-packages/tensorflow/python/keras/engine/training_v1.py", line 2078, in _make_execution_function
    self._make_train_function()
  File "/Users/andreas/tensorflow_macos_venv/lib/python3.8/site-packages/tensorflow/python/keras/engine/training_v1.py", line 2009, in _make_train_function
    updates = self.optimizer.get_updates(
  File "/Users/andreas/tensorflow_macos_venv/lib/python3.8/site-packages/tensorflow/python/keras/optimizer_v2/optimizer_v2.py", line 727, in get_updates
    grads = self.get_gradients(loss, params)
  File "/Users/andreas/tensorflow_macos_venv/lib/python3.8/site-packages/tensorflow/python/keras/optimizer_v2/optimizer_v2.py", line 716, in get_gradients
    grads = gradients.gradients(loss, params)
  File "/Users/andreas/tensorflow_macos_venv/lib/python3.8/site-packages/tensorflow/python/ops/gradients_impl.py", line 169, in gradients
    return gradients_util._GradientsHelper(
  File "/Users/andreas/tensorflow_macos_venv/lib/python3.8/site-packages/tensorflow/python/ops/gradients_util.py", line 714, in _GradientsHelper
    raise ValueError(
ValueError: Incompatible shapes between op input and calculated input gradient.  Forward operation: up_sampling2d/MLCUpsample2D.  Input index: 0. Original input shape: (16, 128, 128, 256).  Calculated input gradient shape: (16, 128, 256, 256)

**Comment by anna-tikhonova** [comment]
Thank you very much for reporting this issue. Could you provide a full reproducible test case that we could run locally?

**Comment by Andreasgejlm** [comment]
Certainly. The following code reproduces the up_sampling2d error when run in the Tensorflow_macos venv:

```
import tensorflow as tf
import numpy as np
from tensorflow.keras import Model, Input, layers, optimizers, utils, losses
tf.compat.v1.disable_eager_execution()

training_data = np.random.rand(32, 256, 256, 3)
y_true = np.random.rand(32, 256, 256, 2)

val_data = np.random.rand(32, 256, 256, 3)

batch_size = 32

train_in = Input((256, 256, 3), name='Input', batch_size=batch_size)
x = layers.Conv2D(128, (3, 3), activation='relu', padding='same')(train_in)
x = layers.MaxPooling2D((2, 2))(x)
x = layers.Conv2D(256, (3, 3), activation='relu', padding='same')(x)
x = layers.UpSampling2D()(x)
x = layers.Conv2D(128, (3, 3), activation='relu', padding='same')(x)


real_branch = layers.Conv2D(128, (3, 3), activation='relu', padding='same')(x)
real_branch = layers.Conv2D(1, (3, 3), activation='relu', padding='same', name="real")(real_branch)
imag_branch = layers.Conv2D(128, (3, 3), activation='relu', padding='same')(x)
imag_branch = layers.Conv2D(1, (3, 3), activation='relu', padding='same', name="imag")(imag_branch)
concat = layers.concatenate([real_branch, imag_branch], axis=3)

model = Model(train_in, concat)

model.summary()
model.compile(optimizer=optimizers.Adam(), loss=losses.mean_squared_error, metrics=['acc'])
model.fit(training_data, y_true, epochs=3, batch_size=batch_size, validation_data=(val_data, y_true))
```

**Comment by anna-tikhonova** [comment]
Thank you for providing the code. We will investigate this issue and get back to you.

**Comment by pooyadavoodi** [comment]
@Andreasgejlm I just verified that this issue is resolved in versions >= v0.1alpha1 of our release. Could you please confirm this.
