### ISSUE TITLE
can't resolve `import tensorflow` in PyCharm

### ISSUE THREAD

**Issue by pekoWang** [apple/tensorflow_macos#47]
I have configured tensorflow_macos, and the test is successful locally, but I cannot import tensorflow when I use PyCharm;
I refer to related articles: https://youtrack.jetbrains.com/issue/PY-29580?_ga=2.84740368.88237636.1606896657-1728153029.1606494024 but it doesn't solve my problem. When I output'LD_LIBRARY_PATH' on the console, I didn't get any feedback.

**Comment by danielmbradley** [comment]
@pekoWang How did you set up the pycharm project? Did you create the python virtual environment first using the script in this repo then mark the created environment as your pycharm project environment when you created it?

**Comment by wenmin-wu** [comment]
It's because the `tensorflow` doesn't exist in your `sys.path`.

**Comment by pekoWang** [comment]
> @pekoWang How did you set up the pycharm project? Did you create the python virtual environment first using the script in this repo then mark the created environment as your pycharm project environment when you created it?

Yes, I have created a virtual environment and passed the terminal test. When using pycharm, I also imported the virtual environment (pycharm). The terminal shows that I am already in the virtual environment of tensorflow, but I still can't use pcharm.` import tensorflow`

this is my terminal
```shell
Last login: Thu Dec  3 14:50:25 on console
wangpeike@wangpeikedeMac-mini ~ % cd tensorflow_macos_venv 
wangpeike@wangpeikedeMac-mini tensorflow_macos_venv % source bin/activate
(tensorflow_macos_venv) wangpeike@wangpeikedeMac-mini tensorflow_macos_venv % python
Python 3.8.2 (default, Oct  2 2020, 10:45:41) 
[Clang 12.0.0 (clang-1200.0.32.27)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow
>>> os.environ['PATH']
'/Users/wangpeike/tensorflow_macos_venv/bin:/Users/wangpeike/opt/anaconda3/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin'
```
and this is my pycharm:
```shell
(tensorflow_macos_venv) wangpeike@wangpeikedeMac-mini pythonProject % python
Python 3.8.2 (default, Oct  2 2020, 10:45:42) 
[Clang 12.0.0 (clang-1200.0.32.27)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> os.environ['PATH']
'/Users/wangpeike/tensorflow_macos_venv/bin:/Users/wangpeike/opt/anaconda3/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin'

>>> import tensorflow
Traceback (most recent call last):
  File "/Users/wangpeike/tensorflow_macos_venv/lib/python3.8/site-packages/tensorflow/python/pywrap_tensorflow.py", line 64, in <module>
    from tensorflow.python._pywrap_tensorflow_internal import *
ImportError: dlopen(/Users/wangpeike/tensorflow_macos_venv/lib/python3.8/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so, 6): no suitable image found.  Did find:
        /Users/wangpeike/tensorflow_macos_venv/lib/python3.8/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so: mach-o, but wrong architecture
        /Users/wangpeike/tensorflow_macos_venv/lib/python3.8/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so: mach-o, but wrong architecture

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/wangpeike/tensorflow_macos_venv/lib/python3.8/site-packages/tensorflow/__init__.py", line 41, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "/Users/wangpeike/tensorflow_macos_venv/lib/python3.8/site-packages/tensorflow/python/__init__.py", line 39, in <module>
    from tensorflow.python import pywrap_tensorflow as _pywrap_tensorflow
  File "/Users/wangpeike/tensorflow_macos_venv/lib/python3.8/site-packages/tensorflow/python/pywrap_tensorflow.py", line 83, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "/Users/wangpeike/tensorflow_macos_venv/lib/python3.8/site-packages/tensorflow/python/pywrap_tensorflow.py", line 64, in <module>
    from tensorflow.python._pywrap_tensorflow_internal import *
ImportError: dlopen(/Users/wangpeike/tensorflow_macos_venv/lib/python3.8/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so, 6): no suitable image found.  Did find:
        /Users/wangpeike/tensorflow_macos_venv/lib/python3.8/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so: mach-o, but wrong architecture
        /Users/wangpeike/tensorflow_macos_venv/lib/python3.8/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so: mach-o, but wrong architecture


Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.
```
and this is my config
![image](https://user-images.githubusercontent.com/68587497/101109554-200d8400-3612-11eb-9418-007aabf8fafc.png)

**Comment by pekoWang** [comment]
> It's because the `tensorflow` doesn't exist in your `sys.path`. It's more about your env configuration problem.

My environment in the terminal and pycharm are the same, because I manually added pycharm after outputting the environment variables in the terminal, but that didn't help. Where else should I check my environment?

**Comment by godkaieethu** [comment]
same issue.do you succeed in importing TensorFlow now?

**Comment by pekoWang** [comment]
> same issue.do you succeed in importing TensorFlow now?

not yet . I will @ u if I fix it

**Comment by TheRealDrCharles** [comment]
same issue, quite strange

**Comment by djessy-atta** [comment]
Same issue but with jupyter lab
