### ISSUE TITLE
SIGILL when importing/using TensorFlow due to wrong architecture (TensorFlow Internal)

### ISSUE THREAD

**Issue by thecsw** [apple/tensorflow_macos#65]
Good morning, everyone! I have an interesting issue that I'm able to resolve. I have M1 MacBook since November 16th and installed this TensorFlow version on that very day. It was working fine and now I decided to reinstall it because some of optimization flags were turned off. By simply running the install script from the readme.

Everything was well and swell while installing, activating the virtual environment is no issue. However, actually trying to use tensor flow with venv's python causes it to crash due to SIGILL

```
TensorFlow and TensorFlow Addons with ML Compute for macOS 11.0 successfully installed.

To begin, activate the virtual environment:

   . "/Users/thecsw/gits/tensorflow_macos_venv/bin/activate"

λ ~/ /Users/thecsw/gits/tensorflow_macos_venv/bin/python3 -m pip install --upgrade pip
Requirement already satisfied: pip in ./gits/tensorflow_macos_venv/lib/python3.8/site-packages (20.3.1)

λ ~/ . "/Users/thecsw/gits/tensorflow_macos_venv/bin/activate"

(tensorflow_macos_venv) λ ~/ python
Python 3.8.6 (default, Nov 20 2020, 23:57:10)
[Clang 12.0.0 (clang-1200.0.32.27)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow
Traceback (most recent call last):
  File "/Users/thecsw/gits/tensorflow_macos_venv/lib/python3.8/site-packages/tensorflow/python/pywrap_tensorflow.py", line 64, in <module>
    from tensorflow.python._pywrap_tensorflow_internal import *
ImportError: dlopen(/Users/thecsw/gits/tensorflow_macos_venv/lib/python3.8/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so, 6): no suitable image found.  Did find:
	/Users/thecsw/gits/tensorflow_macos_venv/lib/python3.8/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so: mach-o, but wrong architecture
	/Users/thecsw/gits/tensorflow_macos_venv/lib/python3.8/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so: mach-o, but wrong architecture

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/thecsw/gits/tensorflow_macos_venv/lib/python3.8/site-packages/tensorflow/__init__.py", line 41, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "/Users/thecsw/gits/tensorflow_macos_venv/lib/python3.8/site-packages/tensorflow/python/__init__.py", line 39, in <module>
    from tensorflow.python import pywrap_tensorflow as _pywrap_tensorflow
  File "/Users/thecsw/gits/tensorflow_macos_venv/lib/python3.8/site-packages/tensorflow/python/pywrap_tensorflow.py", line 83, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "/Users/thecsw/gits/tensorflow_macos_venv/lib/python3.8/site-packages/tensorflow/python/pywrap_tensorflow.py", line 64, in <module>
    from tensorflow.python._pywrap_tensorflow_internal import *
ImportError: dlopen(/Users/thecsw/gits/tensorflow_macos_venv/lib/python3.8/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so, 6): no suitable image found.  Did find:
	/Users/thecsw/gits/tensorflow_macos_venv/lib/python3.8/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so: mach-o, but wrong architecture
	/Users/thecsw/gits/tensorflow_macos_venv/lib/python3.8/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so: mach-o, but wrong architecture


Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.
>>>

(tensorflow_macos_venv) λ ~/ uname -a
Darwin Mania.local 20.1.0 Darwin Kernel Version 20.1.0: Sat Oct 31 00:07:10 PDT 2020; root:xnu-7195.50.7~2/RELEASE_ARM64_T8101 arm64

(tensorflow_macos_venv) λ ~/
```

**Comment by danielplatt** [comment]
You write you are able to resolve the problem. How do you resolve the problem? I have it too.

**Comment by hoytak** [comment]
Hello @thecsw,

Could you send me the output of `file $(which python)` while in your virtual environment?  There are two cpu subtypes for executables on the M1, arm64 and arm64e, and trying to mix the two results in the error you see.  For this pre-release version, we're focusing support on the arm64 version of python in the [Xcode Command Line Tools](https://developer.apple.com/download/more/?=command%20line%20tools), and the included wheel does not include an arm64e slice.  Could you try with that version?

**Comment by thecsw** [comment]
> You write you are able to resolve the problem. How do you resolve the problem? I have it too.

Can you imagine that instead of "not able" I typed in "able"! I'm not able to resolve this

**Comment by thecsw** [comment]
@hoytak very odd, getting x86 binary:
```
(tensorflow_macos_venv) λ ~/ file $(which python)
/Users/thecsw/gits/tensorflow_macos_venv/bin/python: Mach-O 64-bit executable x86_64
```

I have python3.8 installed by brew, but I'm using the Rosetta terminal to run x86 brew. I can't install python 3.8 through arm brew (`/opt/homebrew`) because it simply doesn't build when installing

**Comment by thecsw** [comment]
I got it working now! I had to pass in the python3.8 arm executable from Xcode command line tools
```
λ ~/ which python3.8
/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/bin/python3.8

λ ~/ file $(which python3.8)
/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/bin/python3.8: Mach-O universal binary with 2 architectures: [x86_64:Mach-O 64-bit executable x86_64] [arm64:Mach-O 64-bit executable arm64]
/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/bin/python3.8 (for architecture x86_64):	Mach-O 64-bit executable x86_64
/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/bin/python3.8 (for architecture arm64):	Mach-O 64-bit executable arm64
```

I'm actually seeing 6-8x improvements on some CNN code I have!

I think we're still very green, as even matplotlib or Pillow don't work yet because of some missing symbols

```
(tensorflow_macos_venv) λ ~/ ptpython3.8
>>> import matplotlib.pyplot as plt
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/thecsw/gits/tensorflow_macos_venv/lib/python3.8/site-packages/matplotlib/pyplot.py", line 36, in <module>
    import matplotlib.colorbar
  File "/Users/thecsw/gits/tensorflow_macos_venv/lib/python3.8/site-packages/matplotlib/colorbar.py", line 44, in <module>
    import matplotlib.contour as contour
  File "/Users/thecsw/gits/tensorflow_macos_venv/lib/python3.8/site-packages/matplotlib/contour.py", line 17, in <module>
    import matplotlib.text as text
  File "/Users/thecsw/gits/tensorflow_macos_venv/lib/python3.8/site-packages/matplotlib/text.py", line 16, in <module>
    from .textpath import TextPath  # Unused, but imported by others.
  File "/Users/thecsw/gits/tensorflow_macos_venv/lib/python3.8/site-packages/matplotlib/textpath.py", line 11, in <module>
    from matplotlib.mathtext import MathTextParser
  File "/Users/thecsw/gits/tensorflow_macos_venv/lib/python3.8/site-packages/matplotlib/mathtext.py", line 27, in <module>
    from PIL import Image
  File "/Users/thecsw/gits/tensorflow_macos_venv/lib/python3.8/site-packages/PIL/Image.py", line 94, in <module>
    from . import _imaging as core
ImportError: dlopen(/Users/thecsw/gits/tensorflow_macos_venv/lib/python3.8/site-packages/PIL/_imaging.cpython-38-darwin.so, 2): Symbol not found: _jpeg_resync_to_restart
  Referenced from: /Users/thecsw/gits/tensorflow_macos_venv/lib/python3.8/site-packages/PIL/_imaging.cpython-38-darwin.so
  Expected in: flat namespace
 in /Users/thecsw/gits/tensorflow_macos_venv/lib/python3.8/site-packages/PIL/_imaging.cpython-38-darwin.so

dlopen(/Users/thecsw/gits/tensorflow_macos_venv/lib/python3.8/site-packages/PIL/_imaging.cpython-38-darwin.so, 2): Symbol not found: _jpeg_resync_to_restart
  Referenced from: /Users/thecsw/gits/tensorflow_macos_venv/lib/python3.8/site-packages/PIL/_imaging.cpython-38-darwin.so
  Expected in: flat namespace
 in /Users/thecsw/gits/tensorflow_macos_venv/lib/python3.8/site-packages/PIL/_imaging.cpython-38-darwin.so
```

**Comment by danielplatt** [comment]
Can you say what do you mean by "pass in the python3.8 arm executable from Xcode command line tools"? Where did you pass it and how can I do that?

And does that mean I cannot use virtual environments?

**Comment by thecsw** [comment]
@danielplatt Whenever I run the script, it errors out as my default python on the system isn't python3.8, so I have to pass my arm python3.8 manually, through a `--python` flag. I found mine using find, so
```
find / -type f -name "python3.8" 2>/dev/null
```
Of course you can! When you pass in a good version of python to the script, your virtualenv will have the python3.8 exec. So when you activate the environment, it will add its own python exec to PATH

**Comment by danielplatt** [comment]
@thecsw I appreciate the answer, but I'm not sure I understand. You mean you downloaded version v0.1alpha1 of tensorflow_macos, and then run

`/bin/bash ./tensorflow_macos/install_venv.sh --python <Path to your ARM Python executable>`

Then run python3 and any code involving tensorflow, such as

`import tensorflow`

If I do this, I now get the following new error message: 

`zsh: illegal hardware instruction  python3`

But that's still not my dream result for running the code `import tensorflow`. I also ran the command `file $(which python)`, and the result was: 

```
/Users/xxx/bin/python (for architecture x86_64):        Mach-O 64-bit executable x86_64
/Users/xxx/bin/python (for architecture arm64): Mach-O 64-bit executable arm64
```

But I don't know what all these things mean. Did I make a mistake when following your step-by-step guide? And I know this is probably not the right platform to ask the following question, but do you know of a way to use tensorflow with rosetta?

**Comment by thecsw** [comment]
@danielplatt I may see what's happening, are you running your terminal in arm64 mode? You can check that by running `uname -m`. I have two terminal apps, one running natively, and the other one through rosetta. If I run the command on my native terminal, I get
```
λ ~/ uname -m
arm64
```
the rosetta one yields
```
λ ~/ uname -m
x86_64
```

When I activate my venv, I get the same output as you do
```

λ ~/ . "/Users/.../tensorflow_macos_venv/bin/activate"

(tensorflow_macos_venv) λ ~/ file $(which python)
/Users/.../tensorflow_macos_venv/bin/python: Mach-O universal binary with 2 architectures: [x86_64:Mach-O 64-bit executable x86_64] [arm64:Mach-O 64-bit executable arm64]
/Users/.../tensorflow_macos_venv/bin/python (for architecture x86_64):	Mach-O 64-bit executable x86_64
/Users/.../tensorflow_macos_venv/bin/python (for architecture arm64):	Mach-O 64-bit executable arm64
``` 

And by having that python exec from my environment and a native terminal, I can import tensor flow:
```
(tensorflow_macos_venv) λ ~/ uname -m
arm64

(tensorflow_macos_venv) λ ~/ python
Python 3.8.2 (default, Nov  4 2020, 21:23:28)
[Clang 12.0.0 (clang-1200.0.32.28)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow
>>> tensorflow.__version__
'2.4.0-rc0'
```

If I try to import tensor flow from my rosetta terminal (emulated x86), I get an ungodly error:
```
(tensorflow_macos_venv) λ ~/ uname -m
x86_64

(tensorflow_macos_venv) λ ~/ python
Python 3.8.2 (default, Nov  4 2020, 21:23:28)
[Clang 12.0.0 (clang-1200.0.32.28)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow
Traceback (most recent call last):
  File "/Users/.../tensorflow_macos_venv/lib/python3.8/site-packages/tensorflow/python/pywrap_tensorflow.py", line 64, in <module>

(...The rest of traceback telling me its the wrong architecture and an illegal instruction attempt...)
```

**Comment by danielplatt** [comment]
That was indeed my problem. Thank you very much for the help!

**Comment by ThomasMerkh** [comment]
@thecsw Would you mind helping me out by listing exactly how to "pass my arm python3.8 manually"? I am getting the same errors as above.

When I run
```
find / -type f -name "python3.8" 2>/dev/null
```
it results in 
/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/bin/python3.8
as well as a few other outputs involving anaconda installations and so on.

When I am in the native terminal, no venvs, no conda envs, just the base system, I get that 
```
uname -m
```
results in "arm64".

Then
```
 file $(which python)
```
results in 

/usr/bin/python: Mach-O universal binary with 2 architectures: [x86_64:Mach-O 64-bit executable x86_64] [arm64e:Mach-O 64-bit executable arm64e]
/usr/bin/python (for architecture x86_64):	Mach-O 64-bit executable x86_64
/usr/bin/python (for architecture arm64e):	Mach-O 64-bit executable arm64e

I have been trying to install TF using the command 
```
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/apple/tensorflow_macos/master/scripts/download_and_install.sh)"
```

Once I install it and activate the tensorflow_macos_venv, I open up python, and import tensorflow gives the message:

File "/Users/merkh/tensorflow_macos_venv/lib/python3.8/site-packages/tensorflow/python/pywrap_tensorflow.py", line 64, in <module>
    from tensorflow.python._pywrap_tensorflow_internal import *
ImportError: dlopen(/Users/merkh/tensorflow_macos_venv/lib/python3.8/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so, 6): no suitable image found.  Did find:
	/Users/merkh/tensorflow_macos_venv/lib/python3.8/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so: mach-o, but wrong architecture
	/Users/merkh/tensorflow_macos_venv/lib/python3.8/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so: mach-o, but wrong architecture

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/merkh/tensorflow_macos_venv/lib/python3.8/site-packages/tensorflow/__init__.py", line 41, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "/Users/merkh/tensorflow_macos_venv/lib/python3.8/site-packages/tensorflow/python/__init__.py", line 39, in <module>
    from tensorflow.python import pywrap_tensorflow as _pywrap_tensorflow
  File "/Users/merkh/tensorflow_macos_venv/lib/python3.8/site-packages/tensorflow/python/pywrap_tensorflow.py", line 83, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "/Users/merkh/tensorflow_macos_venv/lib/python3.8/site-packages/tensorflow/python/pywrap_tensorflow.py", line 64, in <module>
    from tensorflow.python._pywrap_tensorflow_internal import *
ImportError: dlopen(/Users/merkh/tensorflow_macos_venv/lib/python3.8/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so, 6): no suitable image found.  Did find:
	/Users/merkh/tensorflow_macos_venv/lib/python3.8/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so: mach-o, but wrong architecture
	/Users/merkh/tensorflow_macos_venv/lib/python3.8/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so: mach-o, but wrong architecture
Failed to load the native TensorFlow runtime.

If you'd be so kind as to walk me through the steps I need to take to have apple's tf version properly installed, that would be very helpful.

**Comment by bforblack** [comment]
I am still facing this issue , any help ?

**Comment by vishalsharma345** [comment]
I have also faced same issue and able to solve this.
try to check architecture, if your system is using this x86_64 architecture
λ ~/ uname -m
x86_64
then,
        Go to Utilities -> right click on terminal -> Get info and uncheck(Open using Rosetta) and quit the terminal.
And try to check architecture
λ ~/ uname -m
arm64
then, 
         1) Create virtual env (python3 -m venv tensorflow) using python3.8
         2) Download tensorflow_macos-0.1alpha3.tar.gz. (https://github.com/apple/tensorflow_macos/releases)
         3) Open Zip and run in terminal (/Users/vishalsharma/Downloads/tensorflow_macos/install_venv.sh -p)
         (tensorflow) vishalsharma@Vishals-MacBook-Air Desktop % python 
          Python 3.8.8 | packaged by conda-forge | (default, Feb 20 2021, 15:50:57) 
         [Clang 11.0.1 ] on darwin
         Type "help", "copyright", "credits" or "license" for more information.
          >>> import tensorflow as tf
          >>> tf.__version__
         '2.4.0-rc0'

**Comment by RemeAjayi** [comment]
> @hoytak very odd, getting x86 binary:
> 
> ```
> (tensorflow_macos_venv) λ ~/ file $(which python)
> /Users/thecsw/gits/tensorflow_macos_venv/bin/python: Mach-O 64-bit executable x86_64
> ```
> 
> I have python3.8 installed by brew, but I'm using the Rosetta terminal to run x86 brew. I can't install python 3.8 through arm brew (`/opt/homebrew`) because it simply doesn't build when installing

Hello, I am unable to import tensorflow and I am getting the exact output quoted above in my virtual environment. I have read the replies severally and I still do not understand how to "pass in the python3.8 arm executable from Xcode command line tools"

After running `find / -type f -name "python3.8" 2>/dev/null`
I get this output 

`/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/bin/python3.8
/System/Volumes/Data/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/bin/python3.8
/System/Volumes/Data/Users/olohireme/miniforge3/pkgs/python-3.8.8-h12cc5a1_0_cpython/bin/python3.8
/System/Volumes/Data/Users/olohireme/miniforge3/envs/tensorflow_macos/bin/python3.8
/System/Volumes/Data/Users/olohireme/opt/anaconda3/bin/python3.8
/System/Volumes/Data/Users/olohireme/opt/anaconda3/pkgs/python-3.8.2-hc70fcce_0/bin/python3.8
/System/Volumes/Data/Users/olohireme/opt/anaconda3/pkgs/python-3.8.5-h26836e1_1/bin/python3.8
/System/Volumes/Data/Users/olohireme/opt/anaconda3/pkgs/python-3.8.8-h88f2d9e_5/bin/python3.8
/System/Volumes/Data/Users/olohireme/opt/anaconda3/envs/tf_final/bin/python3.8
/Users/olohireme/miniforge3/pkgs/python-3.8.8-h12cc5a1_0_cpython/bin/python3.8
/Users/olohireme/miniforge3/envs/tensorflow_macos/bin/python3.8
/Users/olohireme/opt/anaconda3/bin/python3.8
/Users/olohireme/opt/anaconda3/pkgs/python-3.8.2-hc70fcce_0/bin/python3.8
/Users/olohireme/opt/anaconda3/pkgs/python-3.8.5-h26836e1_1/bin/python3.8
/Users/olohireme/opt/anaconda3/pkgs/python-3.8.8-h88f2d9e_5/bin/python3.8
/Users/olohireme/opt/anaconda3/envs/tf_final/bin/python3.8`

I tried to use the first path like this 
`/bin/bash ./tensorflow_macos/install_venv.sh --python /Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/bin/python3.8`, but I am told that the directory does not exist. 

Please can you explain step by step what I need to do to use the right python path. I am a beginner to Data Science and I just got this Mac M1. Thank you.
