### ISSUE TITLE
problems with keras

### ISSUE THREAD

**Issue by HuniPark** [apple/tensorflow_macos#75]
after installing this and trying to run a python file, I get this:
```
Traceback (most recent call last):
  File "/usr/local/bin/python3/lib/python3.8/site-packages/tensorflow/python/pywrap_tensorflow.py", line 64, in <module>
    from tensorflow.python._pywrap_tensorflow_internal import *
ImportError: dlopen(/usr/local/bin/python3/lib/python3.8/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so, 6): no suitable image found.  Did find:
        /usr/local/bin/python3/lib/python3.8/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so: mach-o, but wrong architecture
        /usr/local/bin/python3/lib/python3.8/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so: mach-o, but wrong architecture

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/python3/lib/python3.8/site-packages/keras/__init__.py", line 3, in <module>
    from tensorflow.keras.layers.experimental.preprocessing import RandomRotation
  File "/usr/local/bin/python3/lib/python3.8/site-packages/tensorflow/__init__.py", line 41, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "/usr/local/bin/python3/lib/python3.8/site-packages/tensorflow/python/__init__.py", line 39, in <module>
    from tensorflow.python import pywrap_tensorflow as _pywrap_tensorflow
  File "/usr/local/bin/python3/lib/python3.8/site-packages/tensorflow/python/pywrap_tensorflow.py", line 83, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "/usr/local/bin/python3/lib/python3.8/site-packages/tensorflow/python/pywrap_tensorflow.py", line 64, in <module>
    from tensorflow.python._pywrap_tensorflow_internal import *
ImportError: dlopen(/usr/local/bin/python3/lib/python3.8/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so, 6): no suitable image found.  Did find:
        /usr/local/bin/python3/lib/python3.8/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so: mach-o, but wrong architecture
        /usr/local/bin/python3/lib/python3.8/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so: mach-o, but wrong architecture


Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "example_source.py", line 5, in <module>
    from keras.models import Sequential
  File "/usr/local/bin/python3/lib/python3.8/site-packages/keras/__init__.py", line 5, in <module>
    raise ImportError(
ImportError: Keras requires TensorFlow 2.2 or higher. Install TensorFlow via `pip install tensorflow`

```

This is strange because the cause is the following:

```
from keras.models import Sequential
from keras.layers import Dense
from keras.optimizers import Adam
```

All I'm doing is importing and I can't even do that.

I tried to run the file on normal tensorflow 2.4, but I'm running into 
```
Process finished with exit code 132 (interrupted by signal 4: SIGILL)
```
which basically just means I can't run my file on my machine.

**Comment by IAINATTWATER** [comment]
Try importing Keras from the Tensorflow package (i.e. import TensorFlow.keras)
