### ISSUE TITLE
Wrong Architecture Error on M1

### ISSUE THREAD

**Issue by mwidjaja1** [apple/tensorflow_macos#8]
When trying to run a script which imports Tensorflow on an M1 Macbook Air I get:

```
Traceback (most recent call last):
  File "/Users/Matthew/Documents/mac-benchmark/deeplearn_tf.py", line 7, in <module>
    import tensorflow as tf
  File "/Users/Matthew/tensorflow_macos_venv/lib/python3.8/site-packages/tensorflow/__init__.py", line 41, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "/Users/Matthew/tensorflow_macos_venv/lib/python3.8/site-packages/tensorflow/python/__init__.py", line 39, in <module>
    from tensorflow.python import pywrap_tensorflow as _pywrap_tensorflow
  File "/Users/Matthew/tensorflow_macos_venv/lib/python3.8/site-packages/tensorflow/python/pywrap_tensorflow.py", line 83, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "/Users/Matthew/tensorflow_macos_venv/lib/python3.8/site-packages/tensorflow/python/pywrap_tensorflow.py", line 64, in <module>
    from tensorflow.python._pywrap_tensorflow_internal import *
ImportError: dlopen(/Users/Matthew/tensorflow_macos_venv/lib/python3.8/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so, 6): no suitable image found.  Did find:
	/Users/Matthew/tensorflow_macos_venv/lib/python3.8/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so: mach-o, but wrong architecture
	/Users/Matthew/tensorflow_macos_venv/lib/python3.8/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so: mach-o, but wrong architecture


Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

```

My `sw_vers` say:
ProductName:	macOS
ProductVersion:	11.0
BuildVersion:	20A2411

**Comment by hoytak** [comment]
Hello @mwidjaja1, 

Could you tell me the output of `file $(which python)` ?  Also, can you tell me more about your python distribution?  Did it come as part of the Xcode command line tools?  

Thanks!

**Comment by mwidjaja1** [comment]
Bad News: I kept churning away at the problem so that Python executable I used by now is long gone probably. That said, I tried it both with Python 3.8 from Anaconda (Intel Compiled) and Python 3.7 in /usr/bin which was:

```
/usr/bin/python3: Mach-O universal binary with 2 architectures: [x86_64:Mach-O 64-bit executable x86_64] [arm64e:Mach-O 64-bit executable arm64e]
/usr/bin/python3 (for architecture x86_64):	Mach-O 64-bit executable x86_64
/usr/bin/python3 (for architecture arm64e):	Mach-O 64-bit executable arm64e
```

Good news: I figured it out. I used the new ARM version of Python and its host of packages, in conjunction with your great work with building TensorFlow. I posted my steps in #3

**Comment by hoytak** [comment]
Thank you.  Glad you figured it out.  We're hoping to make this process easier in the future.

**Comment by vivek-ram** [comment]
I got the same issue can u help please

**Comment by basillatif** [comment]
You have duplicate versions of Python installed. Run `which python3` to see where your Python is installed and then remove one of the installations.
